# -*- coding: utf-8 -*-
"""Сгенерировано tools/resolve_icons.py, tools/resolve_addon_icons.py и
tools/resolve_char_icons.py — НЕ править вручную.

Русское имя навыка/аддона/персонажа/силы/предмета -> имя файла иконки на
deadbydaylight.wiki.gg. Иконки НЕ лежат в репозитории: приложение качает их
по мере надобности и кэширует локально (см. IconStore в dbd_icons_store.py).
"""

ICON_BASE = "https://deadbydaylight.wiki.gg/images/"

PERK_ICONS = {
    'Аварийная кнопка': 'IconPerks_deadMansSwitch.png',
    'Адреналин': 'IconPerks_adrenaline.png',
    'Алчность': 'IconPerks_HumanGreed.png',
    'Апокалиптическая смекалка': 'IconPerks_apocalypticIngenuity.png',
    'Аптекарь': 'IconPerks_pharmacy.png',
    'Бада-бада-бум': 'IconsPerks_BadaBadaBoom.png',
    'Барбекю и чили': 'IconPerks_barbecueAndChilli.png',
    'Батарейки в комплекте': 'IconPerks_batteriesIncluded.png',
    'Бац!': 'IconPerks_thwack.png',
    'Без огласки': 'IconPerks_offTheRecord.png',
    'Без пощады': 'IconPerks_noQuarter.png',
    'Без сожаления': 'IconPerks_noMither.png',
    'Безжалостный': 'IconPerks_unrelenting.png',
    'Безжалостный шторм': 'IconPerks_mercilessStorm.png',
    'Безжизненное касание': 'IconPerks_languidTouch.png',
    'Безмолвная тень': 'T_UI_iconsPerks_SilentShadow.png',
    'Безумное упорство': 'IconPerks_madGrit.png',
    'Бессонница': 'IconPerks_vigil.png',
    'Блуждающий взгляд': 'IconPerks_WanderingEye.png',
    'Бремя на себя': 'IconPerks_shoulderTheBurden.png',
    'Быстрая жестокость': 'IconPerks_rapidBrutality.png',
    'Быстрое реагирование': 'IconsPerks_RapidResponse.png',
    'Быстрый гамбит': 'IconPerks_quickGambit.png',
    'Быстрый и тихий': 'IconPerks_quickAndQuiet.png',
    'Вдохновение барда': 'IconPerks_bardicInspiration.png',
    'Везение': 'IconPerks_luckyBreak.png',
    'Визионер': 'IconPerks_visionary.png',
    'Владычество': 'IconPerks_Dominance.png',
    'Вмешательство скверны': 'IconPerks_corruptIntervention.png',
    'Внутренняя сила': 'IconPerks_innerStrength.png',
    'Возмездие': 'IconPerks_nemesis.png',
    'Воин света': 'IconPerks_championOfLight.png',
    'Восприятие экстрасенса': 'IconsPerks_ExtrasensoryPerception.png',
    'Вот это поворот': 'IconPerks_plotTwist.png',
    'Врачебный долг': 'IconsPerks_DutyOfCare.png',
    'Все несвободны': 'IconPerks_NoneAreFree.png',
    'Второе дыхание': 'IconPerks_secondWind.png',
    'Выбор за тобой': 'IconPerks_makeYourChoice.png',
    'Выброс': 'IconPerks_surge.png',
    'Выдержка': 'IconPerks_tenacity.png',
    'Вынужденная нерешительность': 'IconPerks_forcedHesitation.png',
    'Выслеживание подозреваемого': 'IconPerks_stakeOut.png',
    'Выхода нет': 'IconPerks_noWayOut.png',
    'Выше головы': 'IconPerks_bloodRush.png',
    'Генетические ограничения': 'IconPerks_geneticLimits.png',
    'Гибель Франклина': 'IconPerks_franklinsDemise.png',
    'Гибкость': 'IconPerks_lithe.png',
    'Глаза Бельмонта': 'IconPerks_EyesOfBelmont.png',
    'Голод': 'IconPerks_Ravenous.png',
    'Городской бег': 'IconPerks_urbanEvasion.png',
    'Дар: круг исцеления': 'IconPerks_boonCircleOfHealing.png',
    'Дар: непоколебимость': 'T_UI_iconsPerks_BoonSteadfast.png',
    'Дар: освещение': 'IconPerks_boonIllumination.png',
    'Дар: теория мрака': 'IconPerks_boonDarkTheory.png',
    'Дар: уход в тень': 'IconPerks_boonShadowStep.png',
    'Дар: экспонента': 'IconPerks_boonExponential.png',
    'Дедлайн': 'IconPerks_deadline.png',
    'Дежавю': 'IconPerks_dejaVu.png',
    'Дерзость': 'IconPerks_wicked.png',
    'Детективное чутье': 'IconPerks_detectivesHunch.png',
    'Детище света': 'IconPerks_lightborn.png',
    'Детище тьмы': 'IconPerks_shadowborn.png',
    'Диверсия': 'IconPerks_diversion.png',
    'Добивание': 'IconPerks_coupDeGr%C3%A2ce.png',
    'Догонялки': 'IconPerks_gameAfoot.png',
    'Драконья хватка': 'IconPerks_dragonsGrip.png',
    'Драматургия': 'IconPerks_dramaturgy.png',
    'Дружеское состязание': 'IconPerks_friendlyCompetition.png',
    'Друзья до гроба': 'IconPerks_friendsTilTheEnd.png',
    'Дух новичка': 'IconPerks_rookieSpirit.png',
    'Единственный выживший': 'IconPerks_soleSurvivor.png',
    'Железная воля': 'IconPerks_ironWill.png',
    'Железная дева': 'IconPerks_ironMaiden.png',
    'Жестокая изоляция': 'IconPerks_cruelLimits.png',
    'Жизнь в дороге': 'IconPerks_RoadLife.png',
    'Жучок': 'IconPerks_wiretap.png',
    'За чужой счет': 'IconPerks_fastTrack.png',
    'Закалка': 'IconPerks_hardened.png',
    'Замри и увидишь': 'IconPerks_stillSight.png',
    'Запасной игрок': 'IconPerks_backgroundPlayer.png',
    'Записки о призраке': 'IconPerks_GhostNotes.png',
    'Заразительный ужас': 'IconPerks_infectiousFright.png',
    'Зверская сила': 'IconPerks_brutalStrength.png',
    'Зеркальная иллюзия': 'IconPerks_mirroredIllusion.png',
    'Знаток техники': 'IconPerks_gearhead.png',
    'Зов медсестры': 'IconPerks_aNursesCalling.png',
    'Зов на помощь': 'T_UI_iconsPerks_SalvationsCry.png',
    'Игра в открытую': 'IconPerks_open-Handed.png',
    'Изменение плана': 'IconsPerks_ChangeOfPlan.png',
    'Изучение': 'IconPerks_appraisal.png',
    'Им не укрыться': 'IconPerks_nowhereToHide.png',
    'Инстинкт чужого': 'IconPerks_alienInstinct.png',
    'Искажение': 'IconPerks_distortion.png',
    'Истерия': 'IconPerks_hysteria.png',
    'Ищейка': 'IconPerks_bloodhound.png',
    'Как новенький': 'IconPerks_betterThanNew.png',
    'Клоунофобия': 'IconPerks_coulrophobia.png',
    'Коварство': 'IconPerks_insidious.png',
    'Командная работа: быстрая пара': 'IconPerks_teamworkPowerOfTwo.png',
    'Командная работа: общая скрытность': 'IconPerks_teamworkCollectiveStealth.png',
    'Командная работа: полная схема': 'IconsPerks_TeamworkFullCircuit.png',
    'Командная работа: приглушение': 'IconsPerks_TeamworkSoftSpoken.png',
    'Командная работа: скромная победа': 'IconPerks_teamworkToughenUp.png',
    'Командная работа: собраться с силами': 'IconPerks_teamworkThrowDown.png',
    'Корректировка': 'IconPerks_correctiveAction.png',
    'Крепкий орешек': 'IconPerks_deadHard.png',
    'Кровавый договор': 'IconPerks_bloodPact.png',
    'Кровавый смотритель': 'IconPerks_bloodWarden.png',
    'Кровные узы': 'IconPerks_kindred.png',
    'Крушитель': 'IconPerks_saboteur.png',
    'Легковес': 'IconPerks_lightweight.png',
    'Легкоступ': 'IconPerks_light-Footed.png',
    'Лидер': 'IconPerks_leader.png',
    'Ликование': 'IconPerks_Exultation.png',
    'Ловкое приземление': 'IconPerks_balancedLanding.png',
    'Лучшая анатомия': 'IconPerks_superiorAnatomy.png',
    'Лучше вместе': 'IconPerks_betterTogether.png',
    'Любыми средствами': 'IconPerks_anyMeansNecessary.png',
    'Мародерское чутье': 'IconPerks_plunderersInstinct.png',
    'Машинное обучение': 'IconPerks_self-Care.png',
    'Мелкая дичь': 'IconPerks_smallGame.png',
    'Мертвая хватка': 'IconPerks_ironGrasp.png',
    'Место для нас': 'IconsPerks_aPlaceForUs.png',
    'Момент славы': 'IconPerks_MomentOfGlory.png',
    'Мрачные объятья': 'IconPerks_grimEmbrace.png',
    'Мурашки по спине': 'IconPerks_spineChill.png',
    'Мы будем жить вечно': 'IconPerks_wereGonnaLiveForever.png',
    'Мы справимся': 'IconPerks_wellMakeIt.png',
    'Мы тебя видим': 'IconsPerks_WeSeeYou.png',
    'На волю': 'IconPerks_cutLoose.png',
    'На пять шагов впереди': 'IconsPerks_FiveMovesAhead.png',
    'Наблюдение': 'IconPerks_surveillance.png',
    'Надежда': 'IconPerks_hope.png',
    'Напролом': 'IconPerks_headOn.png',
    'Не навреди': 'IconsPerks_DoNoHarm.png',
    'Небесный свидетель': 'T_UI_iconsPerks_CelestialWitness.png',
    'Небрежный мясник': 'IconPerks_sloppyButcher.png',
    'Невыносимое присутствие': 'IconPerks_overwhelmingPresence.png',
    'Незавершенное': 'IconPerks_undone.png',
    'Неистовство': 'T_UI_iconsPerks_Rampage.png',
    'Ненависть': 'IconPerks_rancor.png',
    'Неполадки': 'IconPerks_Haywire.png',
    'Непредвиденное': 'IconPerks_unforeseen.png',
    'Несокрушимый': 'IconPerks_unbreakable.png',
    'Нетерпимость': 'IconPerks_agitation.png',
    'Ниже травы': 'IconPerks_lowProfile.png',
    'Никто не остался позади': 'IconPerks_noOneLeftBehind.png',
    'Нокаут': 'IconPerks_knockOut.png',
    'Нянька': 'IconPerks_babysitter.png',
    'Оберег души': 'IconPerks_soulGuard.png',
    'Обман во благо': 'IconPerks_redHerring.png',
    'Ободрение': 'IconPerks_reassurance.png',
    'Объект одержимости': 'IconPerks_objectOfObsession.png',
    'Оглушительный гром': 'IconPerks_allShakingThunder.png',
    'Одолженное время': 'IconPerks_borrowedTime.png',
    'Оказание помощи': 'T_UI_iconsPerks_LendaHand.png',
    'Опустошение': 'T_UI_iconsPerks_LayWaste.png',
    'Освобождение': 'IconPerks_deliverance.png',
    'Оставленный позади': 'IconPerks_leftBehind.png',
    'Оставьте лучшее напоследок': 'IconPerks_saveTheBestForLast.png',
    'Остаточное проявление': 'IconPerks_residualManifest.png',
    'Отзвук крови': 'IconPerks_bloodEcho.png',
    'Отчаянная борьба': 'IconPerks_powerStruggle.png',
    'Отчаянные меры': 'IconPerks_desperateMeasures.png',
    'Охотник на оленей': 'IconPerks_deerstalker.png',
    'Партнер по сцене': 'IconPerks_scenePartner.png',
    'Перевести часы назад': 'IconsPerks_TurnBackTheClock.png',
    'Перегрузка': 'IconPerks_overcharge.png',
    'Перекрестный допрос': 'T_UI_iconsPerks_CrossExamination.png',
    'Переплетенные навсегда': 'IconPerks_ForeverEntwined.png',
    'Плоды трудов': 'T_UI_iconsPerks_FruitsOfYourLabor.png',
    'Повысить ставки': 'IconPerks_upTheAnte.png',
    'Подрыв': 'IconPerks_eruption.png',
    'Познания в ботанике': 'IconPerks_botanyKnowledge.png',
    'Поиграть со своей жертвой': 'IconPerks_playWithYourFood.png',
    'Полная сосредоточенность': 'IconPerks_hyperfocus.png',
    'Полный газ!': 'T_UI_iconsPerks_WideOpenThrottle.png',
    'Поломка': 'IconPerks_breakdown.png',
    'Помни меня': 'IconPerks_rememberMe.png',
    'Поправка': 'IconPerks_resurgence.png',
    'Порча: благоволение крови': 'IconPerks_hexBloodFavour.png',
    'Порча: в твоей власти': 'T_UI_iconsPerks_HexUnderYourThumb.png',
    'Порча: горькая участь': 'IconPerks_HexWretchedFate.png',
    'Порча: игра для двоих': 'IconPerks_hexTwoCanPlay.png',
    'Порча: игрушка': 'IconPerks_hexPlaything.png',
    'Порча: кара': 'IconPerks_hexRetribution.png',
    'Порча: колыбельная охотницы': 'IconPerks_hexHuntressLullaby.png',
    'Порча: контроль толпы': 'IconPerks_hexCrowdControl.png',
    'Порча: лик мрака': 'IconPerks_hexFaceTheDarkness.png',
    'Порча: не-смерть': 'IconPerks_hexUndying.png',
    'Порча: никому не скрыться от смерти': 'IconPerks_hexNoOneEscapesDeath.png',
    'Порча: охотничий азарт': 'IconPerks_hexThrillOfTheHunt.png',
    'Порча: пентименто': 'IconPerks_hexPentimento.png',
    'Порча: погибель': 'IconPerks_hexRuin.png',
    'Порча: пожирание надежды': 'IconPerks_hexDevourHope.png',
    'Порча: предвестие рока': 'IconPerks_HexOvertureOfDoom.png',
    'Порча: проклятая земля': 'IconPerks_hexHauntedGround.png',
    'Порча: разум улья': 'IconsPerks_HexHiveMind.png',
    'Порча: смертельный испуг': 'T_UI_iconsPerks_ScaredToDeath.png',
    'Порча: только отчаяние': 'IconPerks_NothingButMisery.png',
    'Порча: третья печать': 'IconPerks_hexTheThirdSeal.png',
    'Последний рубеж': 'IconPerks_lastStand.png',
    'Последний этап': 'IconPerks_terminus.png',
    'Поспешное лечение': 'IconPerks_reactiveHealing.png',
    'Потанцуй со мной': 'IconPerks_danceWithMe.png',
    'Потенциальная энергия': 'IconPerks_potentialEnergy.png',
    'Предчувствие': 'IconPerks_premonition.png',
    'Преодоление': 'IconPerks_overcome.png',
    'Преследователь-убийца': 'IconPerks_lethalPursuer.png',
    'Призвание': 'IconPerks_madeForThis.png',
    'Принудительная мера': 'IconPerks_forcedPenance.png',
    'Пристегнись': 'IconPerks_buckleUp.png',
    'Притеснение': 'IconPerks_oppression.png',
    'Проверка на прочность': 'IconPerks_mettleOfMan.png',
    'Проснись': 'IconPerks_wakeUp.png',
    'Противодействие': 'IconPerks_counterforce.png',
    'Прояви себя': 'IconPerks_proveThyself.png',
    'Пугающая тряска': 'IconPerks_thrillingTremors.png',
    'Пугающее присутствие': 'IconPerks_unnervingPresence.png',
    'Равновесие': 'IconPerks_poised.png',
    'Ради людей': 'IconPerks_forThePeople.png',
    'Раз, два, три, четыре!': 'IconPerks_OneTwoThreeFour.png',
    'Разбитые надежды': 'IconPerks_shatteredHope.png',
    'Развитая внимательность': 'IconPerks_awakenedAwareness.png',
    'Разлад': 'IconPerks_discordance.png',
    'Разрушитель разума': 'IconPerks_mindbreaker.png',
    'Раскачка': 'IconPerks_flip-Flop.png',
    'Растворение': 'IconPerks_dissolution.png',
    'Ремонтник': 'IconPerks_troubleshooter.png',
    'Решающий удар': 'IconPerks_decisiveStrike.png',
    'Родительская забота': 'IconPerks_parentalGuidance.png',
    'Розыгрыш': 'IconPerks_bamboozle.png',
    'Рычаг влияния': 'IconPerks_leverage.png',
    'С чистого листа': 'IconPerks_cleanBreak.png',
    'Сам себе доктор': 'IconPerks_self-Care.png',
    'Самосохранение': 'IconPerks_self-Preservation.png',
    'Самоучка': 'IconPerks_autodidact.png',
    'Световая граната': 'IconPerks_flashbang.png',
    'Свирепая гордыня': 'IconPerks_hubris.png',
    'Свободное': 'IconPerks_unbound.png',
    'Связь': 'IconPerks_bond.png',
    'Связь с плетением': 'IconPerks_weaveAttunement.png',
    'Секретный проект': 'IconsPerks_SecretProject.png',
    'Секущий крюк: дар боли': 'IconPerks_scourgeHookGiftOfPain.png',
    'Секущий крюк: пучина ярости': 'IconPerks_scourgeHookFloodsOfRage.png',
    'Секущий крюк: резонанс боли': 'IconPerks_scourgeHookPainResonance.png',
    'Секущий крюк: секрет палача': 'IconPerks_scourgeHookHangmansTrick.png',
    'Секущий крюк: чудовищный храм': 'IconPerks_scourgeHookMonstrousShrine.png',
    'Секущий крюк: щербатый компас': 'IconPerks_scourgeHookJaggedCompass.png',
    'Сеющий страх': 'IconPerks_distressing.png',
    'Сила во мраке': 'IconPerks_strengthInShadows.png',
    'Скользкое мясо': 'IconPerks_slipperyMeat.png',
    'Скопидом': 'IconPerks_hoarder.png',
    'Скрытная погоня': 'IconPerks_furtiveChase.png',
    'Скрытый союз': 'IconPerks_repressedAlliance.png',
    'Слежка и наказание': 'IconPerks_monitorAndAbuse.png',
    'Смертельные узы': 'IconPerks_deathbound.png',
    'Сноровка': 'IconPerks_finesse.png',
    'Собранность': 'IconPerks_innerFocus.png',
    'Совершенное оружие': 'IconPerks_ultimateWeapon.png',
    'Соленое море': 'IconPerks_callOfBrine.png',
    'Солидарность': 'IconPerks_solidarity.png',
    'Состояние потока': 'IconsPerks_FlowState.png',
    'Сострадание': 'IconPerks_empathy.png',
    'Специалист': 'IconPerks_specialist.png',
    'Спокойствие духа': 'IconPerks_calmSpirit.png',
    'Спринтер': 'IconPerks_sprintBurst.png',
    'Стиснув зубы': 'IconPerks_biteTheBullet.png',
    'Стойкий': 'IconPerks_enduring.png',
    'Стридор': 'IconPerks_stridor.png',
    'Строим на века': 'IconPerks_builtToLast.png',
    'Сумеречные шпионы': 'IconPerks_spiesFromTheShadows.png',
    'Счастливая звезда': 'IconPerks_luckyStar.png',
    'Тактика зансин': 'IconPerks_zanshinTactics.png',
    'Танатофобия': 'IconPerks_thanatophobia.png',
    'Темная преданность': 'IconPerks_darkDevotion.png',
    'Темное высокомерие': 'IconPerks_darkArrogance.png',
    'Темное чувство': 'IconPerks_darkSense.png',
    'Территориальный императив': 'IconPerks_territorialImperative.png',
    'Техник': 'IconPerks_technician.png',
    'Тихий шорох': 'IconPerks_bitterMurmur.png',
    'Тлетворное касание': 'IconPerks_septicTouch.png',
    'Товарищество': 'IconPerks_camaraderie.png',
    'Требуются работники': 'IconPerks_HelpWanted.png',
    'Тревога': 'IconPerks_alert.png',
    'Тропа терзаний': 'IconPerks_trailOfTorment.png',
    'Туз в рукаве': 'IconPerks_aceInTheHole.png',
    'Убежденность': 'IconPerks_conviction.png',
    'Угасающий свет': 'IconPerks_dyingLight.png',
    'Ударный забег': 'IconPerks_smashHit.png',
    'Уловка': 'IconPerks_deception.png',
    'Умелец': 'IconPerks_tinkerer.png',
    'Умудренный туманом': 'IconPerks_fogwise.png',
    'Уникальная возможность': 'IconPerks_windowsOfOpportunity.png',
    'Уроки улиц': 'IconPerks_streetwise.png',
    'Усердие': 'IconPerks_overzealous.png',
    'Устойчивость': 'IconPerks_resilience.png',
    'Утилизатор': 'IconPerks_scavenger.png',
    'Уход за больным': 'IconPerks_aftercare.png',
    'Фанатение': 'IconPerks_starstruck.png',
    'Фантомный страх': 'IconPerks_PhantomFear.png',
    'Фиксация': 'IconPerks_fixated.png',
    'Форсаж': 'IconPerks_breakout.png',
    'Фугасная мина': 'IconPerks_blastMine.png',
    'Химическая ловушка': 'IconPerks_chemicalTrap.png',
    'Хищник': 'IconPerks_predator.png',
    'Хищный зверь': 'IconPerks_beastOfPrey.png',
    'Чары: пауки-прядильщики': 'IconPerks_invocationWeavingSpiders.png',
    'Чары: предательские вороны': 'IconPerks_invocationTreacherousCrows.png',
    'Через край': 'IconPerks_boilOver.png',
    'Чертик из табакерки': 'IconPerks_popGoesTheWeasel.png',
    'Чуткий слух': 'IconPerks_imAllEars.png',
    'Шепоты': 'IconPerks_whispers.png',
    'Эй, я здесь!': 'IconPerks_comeAndGetMe.png',
    'Эмпатическая связь': 'IconPerks_empathicConnection.png',
    'Этому не бывать': 'IconPerks_thisIsNotHappening.png',
    'Явление мрака': 'IconPerks_darknessRevealed.png',
    'Яркое пламя': 'IconPerks_fireUp.png',
    'Ярость духа': 'IconPerks_spiritFury.png',
    'Ясновидение': 'IconPerks_clairvoyance.png',
}

ADDON_ICONS = {
    '15-процентный эфир': 'IconAddon_ether15Vol.png',
    'Tir оптика': 'IconAddon_tirOptic.png',
    '«Гоуст Фейс пойман на камеру»': 'IconAddon_caughtOnTape.png',
    '«Дисциплина» — заметки Картера': 'IconAddon_disciplineCartersNotes.png',
    '«Порядок» — заметки Картера': 'IconAddon_orderCartersNotes.png',
    '«Спокойствие» — заметки Картера': 'IconAddon_calmCartersNotes.png',
    '«Усмирение» — заметки Картера': 'IconAddon_restraintCartersNotes.png',
    '«Филадельфия»': 'IconAddon_philly.png',
    'Аварийный шлем': 'IconAddon_emergencyHelmet.png',
    'Автограф Чиуна': 'IconAddon_ji-WoonsAutograph.png',
    'Автопортрет': 'IconAddon_automaticDrawing.png',
    'Агония без названия': 'IconAddon_untitledAgony.png',
    'Адаптивное освещение': 'IconAddon_adaptiveLighting.png',
    'Ади Валенте №1': 'IconAddon_adiValenteIssue1.png',
    'Адресная книга Олсена': 'IconAddon_olsensAddressBook.png',
    'Аккумулятор с мощным зарядом': 'IconAddon_longLifeBattery.png',
    'Алое яйцо': 'IconAddon_scarletEgg.png',
    'Альбом «Край возрождения»': 'IconAddon_edgeOfRevivalAlbum.png',
    'Амулет Якуёкэ': 'IconAddon_yakuyokeAmulet.png',
    'Амулет дружбы': 'IconAddon_friendshipCharm.png',
    'Амулет предотвращения': 'IconAddon_prophylacticAmulet.png',
    'Амулет ревнителя': 'IconAddon_devoteesAmulet.png',
    'Амулет сиавасэ': 'IconAddon_shiawaseAmulet.png',
    'Амулет экзорцизма': 'IconAddon_exorcismAmulet.png',
    'Анализатор уязвимостей': 'IconAddon_vitalTargetingProcessor.png',
    'Ароматный клок волос': 'IconAddon_fragrantTuftOfHair.png',
    'Афиша второсортного фильма': 'IconAddon_b-moviePoster.png',
    'Бабушкин платок': 'IconAddon_flowerBabushka.png',
    'Бабушкино сердце': 'IconAddon_granmasHeart.png',
    'Багровая печать': 'IconAddon_crimsonStamp.png',
    'Банка одиннадцатой': 'IconAddon_elevensSoda.png',
    'Банка пороха': 'IconAddon_gunpowderTin.png',
    'Бант для волос': 'IconAddon_hairBow.png',
    'Бархатная ткань': 'IconAddon_velvetFabric.png',
    'Батарейка': 'IconAddon_battery.png',
    'Беговая обувь': 'IconAddon_runningShoes.png',
    'Безвкусные серьги': 'IconAddon_tackyEarrings.png',
    'Бездонная сумка': 'IconAddon_BagOfHolding.png',
    'Безликий значок-смайлик': 'IconAddon_defacedSmileyPin.png',
    'Бейдж санитара': 'IconAddon_OrderlyID.png',
    'Белый бант': 'IconAddon_whiteHairRibbon.png',
    'Бижутерия': 'IconAddon_jewellery.png',
    'Бинты': 'IconAddon_bandages.png',
    'Бисерный лабиринт': 'IconAddon_BeadMaze.png',
    'Благовонная мазь': 'IconAddon_incensedOintment.png',
    'Блестящий маэдатэ': 'IconAddon_polishedMaedate.png',
    'Блокнот с предложениями': 'IconAddon_notebookOfTheories.png',
    'Бодрые сверчки': 'IconAddon_livelyCrickets.png',
    'Болт самоуничтожения': 'IconAddon_selfDestructBolt.png',
    'Ботинки с железными мысками': 'IconAddon_steelToeBoots.png',
    'Ботиночки Матиаса': 'IconAddon_matiasBabyShoes.png',
    'Браслет администратора': 'IconAddon_adminWristband.png',
    'Браслет дружбы': 'IconAddon_friendshipBracelet.png',
    'Бриллиантовые запонки': 'IconAddon_diamondCufflinks.png',
    'Бритва Виктора': 'IconAddon_VictorsRazorBlade.png',
    'Брюшные повязки': 'IconAddon_abdominalDressing.png',
    'Бумажник Канэки': 'T_UI_iconAddon_KanekisWallet.png',
    'Бурдюк': 'IconAddon_waterskin.png',
    'Бутылка дешевого джина': 'IconAddon_cheapGinBottle.png',
    'Бутылка для вечеринки': 'IconAddon_partyBottle.png',
    'Бутылка хлороформа': 'IconAddon_bottleOfChloroform.png',
    'В ловушке мрака': 'IconAddon_capturedByTheDark.png',
    'В память о Дж. Майерс': 'IconAddon_jMyersMemorial.png',
    'Венок из манника': 'IconAddon_mannaGrassBraid.png',
    'Веревка с узлами': 'IconAddon_knottedRope.png',
    'Вертолетный руль': 'IconAddon_helicopterStick.png',
    'Вещество души': 'IconAddon_soulChemical.png',
    'Видеокассета': 'IconAddon_videoTape.png',
    'Видеомагнитофон': 'IconAddon_vcr.png',
    'Винтажный радиоприемник': 'IconAddon_Mid-CenturyRadio.png',
    'Вирус «Уроборос»': 'IconAddon_uroborosVirus.png',
    'Виски «Голд Крик»': 'IconAddon_goldCreekWhiskey.png',
    'Витражная роспись': 'IconAddon_StainedGlassMural.png',
    'Внутренности Эша': 'IconAddon_ashsInnards.png',
    'Вода из колодца': 'IconAddon_wellWater.png',
    'Водительские права': 'IconAddon_driversLicense.png',
    'Волокна неизвестных растений': 'IconAddon_foreignPlantFibres.png',
    'Волосы медузы': 'IconAddon_MedusasHair.png',
    'Волчок': 'IconAddon_spinningTop.png',
    'Волшебный билет': 'IconAddon_MagicalTicket.png',
    'Вонючие стельки': 'IconAddon_smellyInnerSoles.png',
    'Вороний натюрморт': 'IconAddon_stillLifeCrow.png',
    'Восковая кукла': 'IconAddon_waxDoll.png',
    'Вострый меч': 'IconAddon_SwordOfKass.png',
    'Все на праздник! Плакат': 'IconAddon_CelebratePoster.png',
    'Всевидящий - дух': 'IconAddon_allSeeing-Spirit.png',
    'Всевидящий - кровь': 'IconAddon_allSeeing-Blood.png',
    'Вулканический камень': 'IconAddon_volcanicStone.png',
    'Вымокший ботинок': 'IconAddon_waterloggedShoe.png',
    'Вырезки из газет': 'IconAddon_headlineCut-Outs.png',
    'Высокоамперный усилитель': 'IconAddon_high-CurrentUpgrade.png',
    'Высококлассные сапфировые линзы': 'IconAddon_high-EndSapphireLens.png',
    'Высушенный цветок вишни': 'IconAddon_driedCherryBlossom.png',
    'Вязальная спица': 'T_UI_iconAddon_KnittingNeedle.png',
    'Вяленая конина': 'IconAddon_driedHorsemeat.png',
    'Газета в рамке': 'IconAddon_framedNewspaper.png',
    'Галстук Амона': 'T_UI_iconAddon_AmonsNecktie.png',
    'Гарнитура экипажа': 'IconAddon_crewHeadset.png',
    'Гарпун': 'IconAddon_harpoonGun.png',
    'Гелевые повязки': 'IconAddon_gelDressings.png',
    'Гель с наномашинами': 'IconAddon_nanomachineGel.png',
    'Гематитовая пломба': 'IconAddon_haematiteSeal.png',
    'Генератор голограмм': 'IconAddon_hologramGenerator.png',
    'Генератор красного шума': 'IconAddon_brownNoiseGenerator.png',
    'Гитарные струны Бонни': 'IconAddon_BonniesGuitarStrings.png',
    'Глаз Михаила': 'IconAddon_mikhailsEye.png',
    'Глазастая мантия': 'IconAddon_RobeOfEyes.png',
    'Глазная слизь': 'T_UI_iconAddon_EyeGoop.png',
    'Гнилая свинья': 'IconAddon_rottenSwine.png',
    'Гниющие останки': 'IconAddon_festeringCarrion.png',
    'Голубое платье': 'IconAddon_blueDress.png',
    'Гостевой браслет': 'IconAddon_visitorWristband.png',
    'Гоуст Фейс - сажа': 'IconAddon_theGhost-Soot.png',
    'Грибная смесь': 'IconAddon_mushroomFormula.png',
    'Грубый оселок': 'IconAddon_coarseStone.png',
    'Групповое фото': 'IconAddon_classPhoto.png',
    'Грязная бейсболка': 'IconAddon_muddySportsDayCap.png',
    'Грязные деньги': 'T_UI_iconAddon_DirtyMoney.png',
    'Грязные цепи': 'IconAddon_begrimedChains.png',
    'Грязный нож': 'IconAddon_filthyBlade.png',
    'Губка': 'IconAddon_sponge.png',
    'Густое варево': 'IconAddon_thickTar.png',
    'Дамское зеркало': 'IconAddon_vanityMirror.png',
    'Два гвоздя': 'T_UI_iconAddon_TwoNails.png',
    'Деревянная лиса': 'IconAddon_woodenFox.png',
    'Деревянная лошадка': 'IconAddon_woodenHorse.png',
    'Деревянная маска Они': 'IconAddon_woodenOniMask.png',
    'Детская бейсбольная перчатка': 'IconAddon_kidsBallGlove.png',
    'Детский деревянный меч': 'IconAddon_childsWoodenSword.png',
    'Детский рисунок': 'IconAddon_kidsDrawing.png',
    'Дешевый одеколон': 'IconAddon_cheapCologne.png',
    'Дзори': 'IconAddon_zori.png',
    'Диктофон': 'IconAddon_fieldRecorder.png',
    'Длинное реле для бензопилы': 'IconAddon_longGuideBar.png',
    'Дневник Виго': 'IconAddon_vigosJournal.png',
    'Дневник Джудит': 'IconAddon_judithsJournal.png',
    'Дневник Олсена': 'IconAddon_olsensJournal.png',
    'Дополнительная пружина': 'IconAddon_secondaryCoil.png',
    'Дружба на века': 'IconAddon_bffs.png',
    'Дубовое топорище': 'IconAddon_oakHaft.png',
    'Дымящаяся кассета': 'IconAddon_fumingMixTape.png',
    'Жевательный табак': 'IconAddon_chewingTobacco.png',
    'Желчь чумы': 'IconAddon_plagueBile.png',
    'Жемчужина силы': 'IconAddon_PearlOfPower.png',
    'Жертвенный нож': 'IconAddon_sacrificialKnife.png',
    'Жесткая шляпа': 'IconAddon_hardHat.png',
    'Жестяная масленка': 'IconAddon_tinOilCan.png',
    'Жетон помощника шерифа': 'T_UI_iconAddon_DeputysBadge.png',
    'Жирное мясо': 'IconAddon_fattyMeat.png',
    'Журавль оригами': 'IconAddon_origamiCrane.png',
    'Забрызганный носовой платок': 'IconAddon_spottedHandkerchief.png',
    'Забытая видеокассета': 'IconAddon_forgottenVideotape.png',
    'Завещание': 'IconAddon_lastWill.png',
    'Загадочный эликсир': 'IconAddon_iridescentElixir.png',
    'Зажим для ремня': 'IconAddon_knifeBeltClip.png',
    'Зазубренные челюсти': 'IconAddon_serratedJaws.png',
    'Заостренная опора': 'IconAddon_sharpenedMount.png',
    'Заостренная щепка': 'IconAddon_sharpenedFlint.png',
    'Записка от парня': 'IconAddon_boyfriendsMemo.png',
    'Зараженное рвотное': 'IconAddon_infectedEmetic.png',
    'Затупленный нож': 'IconAddon_dulledKnife.png',
    'Защитные перчатки': 'IconAddon_protectiveGloves.png',
    'Звездная карта Ламберт': 'IconAddon_lambertsStarMap.png',
    'Зверь - сажа': 'IconAddon_theBeast-Soot.png',
    'Зеленая трава': 'IconAddon_greenHerb.png',
    'Зеленая тряпка': 'IconAddon_mintRag.png',
    'Зеленое платье': 'IconAddon_greenDress.png',
    'Зелье скорости': 'IconAddon_PotionOfSpeed.png',
    'Златка': 'IconAddon_jewelBeetle.png',
    'Зловещее рвотное': 'IconAddon_vileEmetic.png',
    'Змей - сажа': 'IconAddon_theSerpent-Soot.png',
    'Значок Легиона': 'IconAddon_theLegionPin.png',
    'Значок охранника': 'IconAddon_SecurityGuardsBadge.png',
    'Значок шерифа': 'IconAddon_marshalsBadge.png',
    'Значок-смайлик': 'IconAddon_smileyFacePin.png',
    'Золотой зуб Бейшора': 'IconAddon_bayshoresGoldTooth.png',
    'Зонтик Хинами': 'T_UI_iconAddon_HinamisUmbrella.png',
    'Зуб щелкунчика': 'IconAddon_chatterersTooth.png',
    'Зубодробилка': 'IconAddon_jawSmasher.png',
    'Ивовый венок': 'IconAddon_willowWreath.png',
    'Иголка и нитка': 'IconAddon_needle&Thread.png',
    'Извивающийся паразит': 'IconAddon_wrigglingParasite.png',
    'Изодранное платье': 'IconAddon_shreddedGown.png',
    'Израсходованная чернильная лента': 'IconAddon_depletedInkRibbon.png',
    'Изуродованная ворона': 'IconAddon_blightedCrow.png',
    'Изуродованная крыса': 'IconAddon_blightedRat.png',
    'Импровизированный электрохлыст': 'IconAddon_improvisedCattleProd.png',
    'Инструмент диагностики (строительство)': 'IconAddon_diagnosticToolConstruction.png',
    'Инструмент пыток': 'T_UI_iconAddon_medicalApparatus.png',
    'Интенсивный галоген': 'IconAddon_intenseHalogen.png',
    'Инфракрасный модуль': 'IconAddon_infraredUpgrade.png',
    'Искаженное фото': 'IconAddon_distortedPhoto.png',
    'Испачканный топор': 'IconAddon_begrimedHead.png',
    'Испорченный метроном': 'IconAddon_defectiveMetronome.png',
    'Иссеченный рюкзак': 'IconAddon_slashedBackpack.png',
    'Исследование колотых ран': 'IconAddon_stabWoundsStudy.png',
    'Исходная боль': 'IconAddon_originalPain.png',
    'Исцеляющая припарка': 'IconAddon_healingPoultice.png',
    'Исчезающая шкатулка': 'IconAddon_vanishingBox.png',
    'Ищейка - сажа': 'IconAddon_theHound-Soot.png',
    'Календарь Хэдди': 'IconAddon_haddiesCalendar.png',
    'Камень для сауны': 'T_UI_iconAddon_SaunaRock.png',
    'Камень призыва': 'IconAddon_summoningStone.png',
    'Камушек беспокойства': 'IconAddon_worryStone.png',
    'Канализационная слякоть': 'IconAddon_sewerSludge.png',
    'Канистра керосина': 'IconAddon_keroseneCan.png',
    'Капля парфюма': 'IconAddon_dropOfPerfume.png',
    'Караульный факел': 'IconAddon_townWatchsTorch.png',
    'Карманные часы': 'IconAddon_PocketWatchVampiricShift.png',
    'Карта жертвы': 'IconAddon_victimsMap.png',
    'Карта с метками': 'IconAddon_markedMap.png',
    'Картридж с жуткой игрой': 'IconAddon_obscureGameCartridge.png',
    'Кассета Джо': 'IconAddon_joeysMixTape.png',
    'Кассета Джули': 'IconAddon_juliesMixTape.png',
    'Кассета Сузи': 'IconAddon_susiesMixTape.png',
    'Кассета Фрэнка': 'IconAddon_franksMixTape.png',
    'Катушка проволоки': 'IconAddon_wireSpool.png',
    'Кепка Бретта': 'IconAddon_brettsCap.png',
    'Кинжал из зуба дракона': 'IconAddon_DragontoothDagger.png',
    'Киноварный паутинник': 'IconAddon_vermilionWebcap.png',
    'Кипарисовое ожерелье': 'IconAddon_cypressNecklet.png',
    'Кислотная кровь': 'IconAddon_acidicBlood.png',
    'Кишки Брайана': 'IconAddon_briansIntestine.png',
    'Кишки мяуса': 'IconAddon_mewsGuts.png',
    'Клейкая паутина': 'IconAddon_viscousWebbing.png',
    'Клоунские перчатки без пальцев': 'IconAddon_fingerlessParadeGloves.png',
    'Клык Варга': 'IconAddon_WargsFang.png',
    'Клык инженера': 'IconAddon_engineersFang.png',
    'Ключ от судна': 'IconAddon_boatKey.png',
    'Ключи начальника тюрьмы': 'IconAddon_wardensKeys.png',
    'Книга «Багровая церемония»': 'IconAddon_crimsonCeremonyBook.png',
    'Книга «Потерянные воспоминания»': 'IconAddon_lostMemoriesBook.png',
    'Книга по дрессировке': 'IconAddon_trainersBook.png',
    'Коготь цербера': 'IconAddon_CerberusTalon.png',
    'Кожаная петля': 'IconAddon_leatherLoop.png',
    'Кожаная рукоять': 'IconAddon_leatherGrip.png',
    'Кожаная сбруя': 'IconAddon_leatherHarness.png',
    'Кожаные ножны': 'IconAddon_leatherKnifeSheath.png',
    'Кожаные перчатки': 'IconAddon_leatherGloves.png',
    'Колодезный камень': 'IconAddon_wellStone.png',
    'Колокольчики тюремщика': 'IconAddon_jailersChimes.png',
    'Колонна терзаний': 'IconAddon_torturePillar.png',
    'Колпак для вечеринок': 'IconAddon_PartyHat.png',
    'Колпак с электродами': 'IconAddon_ElectrodeCap.png',
    'Кольцо алхимика': 'IconAddon_alchemistsRing.png',
    'Кольцо от мамы': 'IconAddon_mother-DaughterRing.png',
    'Кольцо телекинеза': 'IconAddon_RingOfTelekinesis.png',
    'Кольцо хранения заклинаний': 'IconAddon_RingOfSpellStoring.png',
    'Колючая проволока': 'IconAddon_barbedWire.png',
    'Колючее гнездо': 'IconAddon_thornyNest.png',
    'Колючки гледичии': 'IconAddon_honeyLocustThorn.png',
    'Комплект из 4-х спиральных пружин': 'IconAddon_4-coilSpringKit.png',
    'Копченый окунь': 'IconAddon_smokedSnapper.png',
    'Коробка «Хороший парень»': 'IconAddon_goodGuyBox.png',
    'Коробка из-под сигар': 'IconAddon_cigarBox.png',
    'Коробка с бижутерией': 'IconAddon_jewelleryBox.png',
    'Костыль Акито': 'IconAddon_akitosCrutch.png',
    'Кость существа': 'IconAddon_creaturesBone.png',
    'Костяной язычок колокола': 'IconAddon_boneClapper.png',
    'Кофе коронера': 'T_UI_iconAddon_CoronersCoffee.png',
    'Кофейная гуща': 'IconAddon_coffeeGrounds.png',
    'Кофель-нагели': 'IconAddon_belayingPins.png',
    'Кошачий глаз': 'IconAddon_catsEye.png',
    'Кошачья переноска': 'IconAddon_catCarrier.png',
    'Кошелек Олсена': 'IconAddon_olsensWallet.png',
    'Красная кисть': 'IconAddon_redPaintBrush.png',
    'Красная трава': 'IconAddon_redHerb.png',
    'Красноголовая сколопендра': 'T_UI_iconAddon_redHeadedCentipede.png',
    'Красный мох': 'IconAddon_redMoss.png',
    'Красочный некролог': 'IconAddon_vibrantObituary.png',
    'Кремень и сталь': 'IconAddon_flintAndSteel.png',
    'Кремированные останки': 'IconAddon_crematedRemains.png',
    'Крепежные инструменты': 'IconAddon_fasteningTools.png',
    'Крепкая веревка': 'IconAddon_outdoorRope.png',
    'Криогель': 'IconAddon_cryoGel.png',
    'Кровавая грязь': 'IconAddon_bloodiedMud.png',
    'Кровавая пружина': 'IconAddon_bloodyCoil.png',
    'Кровавая улыбка': 'T_UI_iconAddon_BloodySmile.png',
    'Кровавый журнал': 'T_UI_iconAddon_BloodyMagazine.png',
    'Кровавый янтарь': 'IconAddon_bloodAmber.png',
    'Кровоостанавливающий препарат': 'IconAddon_stypticAgent.png',
    'Кровь Ларри': 'IconAddon_larrysBlood.png',
    'Кровь Марвина': 'IconAddon_marvinsBlood.png',
    'Кроличья лапка': 'IconAddon_rabbitsFoot.png',
    'Крошечный скальпель': 'IconAddon_tinyScalpel.png',
    'Крылатая обувь': 'IconAddon_WingedBoots.png',
    'Крысиный яд': 'IconAddon_ratPoison.png',
    'Крюк Фокси': 'IconAddon_FoxyHook.png',
    'Куб Зои': 'IconAddon_CubeOfZoe.png',
    'Кубик с буквой «Z»': 'IconAddon_zBlock.png',
    'Кубик с единорогом': 'IconAddon_unicornBlock.png',
    'Кубик с кошкой': 'IconAddon_catBlock.png',
    'Кубик с овцами': 'IconAddon_sheepBlock.png',
    'Кубок (золотой)': 'IconAddon_chaliceGold.png',
    'Кузнечные щипцы': 'IconAddon_ironworkersTongs.png',
    'Кузнечный молот': 'IconAddon_blacksmithsHammer.png',
    'Кукла-убийца': 'IconAddon_KillerDoll.png',
    'Кукольные глаза': 'IconAddon_dollEyes.png',
    'Кукуруза чокло': 'IconAddon_chocloCorn.png',
    'Кукурузный самогон': 'IconAddon_theThompsonsMix.png',
    'Кусок воска': 'IconAddon_waxBrick.png',
    'Кусок надгробия': 'IconAddon_tombstonePiece.png',
    'Кучка гвоздей': 'IconAddon_pileOfNails.png',
    'Лев, нарисованный тушью': 'IconAddon_inkLion.png',
    'Легкое оленя': 'IconAddon_deerLung.png',
    'Лезвие боевого топора': 'IconAddon_battleAxeHead.png',
    'Лезвия': 'IconAddon_utilityBlades.png',
    'Леопардовая ткань': 'IconAddon_leopardprintFabric.png',
    'Лесное рагу': 'IconAddon_forestStew.png',
    'Лианы образца 43': 'IconAddon_plant43Vines.png',
    'Ликорис лучистый': 'T_UI_iconAddon_redSpiderLily.png',
    'Линейка': 'IconAddon_yardstick.png',
    'Линейка с гравировкой': 'IconAddon_etchedRuler.png',
    'Липкая бутылка из-под газировки': 'IconAddon_stickySodaBottle.png',
    'Липкая пастилка': 'IconAddon_stickyLozenge.png',
    'Липкая слизь': 'IconAddon_stickyLining.png',
    'Лицевая маска': 'IconAddon_faceMask.png',
    'Лохмы': 'IconAddon_clumpOfHair.png',
    'Львиный клык': 'IconAddon_lionFang.png',
    'Ляпис-Лазурь': 'IconAddon_LapisLazuli.png',
    'Маска Ямори': 'T_UI_iconAddon_YamorisMask.png',
    'Масло для растираний': 'IconAddon_rubbingOil.png',
    'Маслянистая пружина': 'IconAddon_oilyCoil.png',
    'Маслянистый сок': 'IconAddon_oilySap.png',
    'Масляные краски': 'IconAddon_oilPaints.png',
    'Медальон белого волка': 'IconAddon_WhiteWolfMedallion.png',
    'Медальон с дамой': 'IconAddon_maidenMedallion.png',
    'Медальон с единорогом': 'IconAddon_unicornMedallion.png',
    'Медальон со львом': 'IconAddon_lionMedallion.png',
    'Медвежий жир': 'IconAddon_bearOil.png',
    'Медицинские ножницы': 'IconAddon_medicalScissors.png',
    'Медная зажигалка': 'IconAddon_brassCaseLighter.png',
    'Мелодичное убийство': 'IconAddon_melodiousMurder.png',
    'Мемориальный цветок': 'IconAddon_memorialFlower.png',
    'Мензурка с отбеливателем': 'IconAddon_flaskOfBleach.png',
    'Мертвый кролик': 'IconAddon_deadRabbit.png',
    'Мерцающий свет': 'IconAddon_strobingLight.png',
    'Мерцающий телевизор': 'IconAddon_flickeringTelevision.png',
    'Метки зверя': 'IconAddon_theBeastsMarks.png',
    'Метки ножом': 'IconAddon_knifeScratches.png',
    'Мешок с шестеренками': 'IconAddon_bagOfGears.png',
    'Мешочек Канэки': 'T_UI_iconAddon_satchel.png',
    'Мизинец рыжей девушки': 'IconAddon_redheadsPinkieFinger.png',
    'Модифицированный таймер': 'IconAddon_tamperedTimer.png',
    'Можжевеловый бонсай': 'IconAddon_juniperBonsai.png',
    'Мокрое от слез тэнугуи': 'IconAddon_tearSoakedTenugui.png',
    'Молочные зубы': 'IconAddon_babyTeeth.png',
    'Монокль со сколами': 'IconAddon_chippedMonocle.png',
    'Монокуляр ночного видения': 'IconAddon_nightVisionMonocular.png',
    'Монтажный пульт': 'IconAddon_tapeEditingDeck.png',
    'Мощная вытяжка': 'IconAddon_potentExtract.png',
    'Мощный прожектор': 'IconAddon_high-PowerFloodlight.png',
    'Мрачная железная маска': 'IconAddon_grimIronMask.png',
    'Музыкальная шкатулка с золушкой': 'IconAddon_cinderellaMusicBox.png',
    'Мягкие челюсти': 'IconAddon_paddedJaws.png',
    'Набедренные ножны': 'IconAddon_drop-LegKnifeSheath.png',
    'Набор правил №2': 'IconAddon_rulesSetNo.2.png',
    'Набор яркого грима': 'IconAddon_garishMake-UpKit.png',
    'Набросок Пилы': 'IconAddon_jigsawsSketch.png',
    'Надгробие Джудит': 'IconAddon_judithsTombstone.png',
    'Напильник для бензопилы': 'IconAddon_chainsawFile.png',
    'Напульсник из «Потрошителя»': 'IconAddon_ripperBrace.png',
    'Наружная камера наблюдения': 'IconAddon_outdoorSecurityCamera.png',
    'Натяжная пружина': 'IconAddon_tensionSpring.png',
    'Наушники Хидэ': 'T_UI_iconAddon_HidesHeadphones.png',
    'Нашатырный спирт': 'IconAddon_spiritOfHartshorn.png',
    'Неаккуратный набросок': 'IconAddon_sketchAttempt.png',
    'Незаконченная карта': 'IconAddon_unfinishedMap.png',
    'Низкой отдачей': 'IconAddon_lowKickbackChains.png',
    'Новая деталь': 'IconAddon_brandNewPart.png',
    'Ножовка': 'IconAddon_hacksaw.png',
    'Носовая фигура': 'IconAddon_shipFigurehead.png',
    'О горечь и любовь моя': 'IconAddon_oGriefOLover.png',
    'Обезображенное ухо': 'IconAddon_disfiguredEar.png',
    'Облегченное шасси': 'IconAddon_lightChassis.png',
    'Образец Т-вируса': 'IconAddon_t-VirusSample.png',
    'Обсидиановый кубок': 'IconAddon_obsidianGoblet.png',
    'Оглушающие динамики': 'IconAddon_shotgunSpeakers.png',
    'Ограничитель для заточки цепи': 'IconAddon_depthGaugeRake.png',
    'Одежда «Дерево Аогири»': 'T_UI_iconAddon_AogiriTreeRobe.png',
    'Ожерелье из болотной орхидеи': 'IconAddon_swampOrchidNecklet.png',
    'Ожерелье с лунным камнем': 'IconAddon_MoonstoneNecklace.png',
    'Окровавленная перчатка Рендзиро': 'IconAddon_renjirosBloodyGlove.png',
    'Окровавленная повязка': 'IconAddon_bloodySash.png',
    'Окровавленные ногти': 'IconAddon_bloodyFingernails.png',
    'Окровавленный конек': 'IconAddon_BloodyRollerSkate.png',
    'Окровавленный носовой платок': 'T_UI_iconAddon_bloodStainedHandkerchief.png',
    'Опасная бритва': 'IconAddon_straightRazor.png',
    'Освежитель воздуха': 'IconAddon_airFreshener.png',
    'Освященное яблоко': 'IconAddon_blessedApple.png',
    'Осколки зеркала': 'T_UI_iconAddon_MirrorShards.png',
    'Осколок зеркала': 'IconAddon_mirrorShard.png',
    'Осколок стекла': 'IconAddon_glassFragment.png',
    'Ослабленные винты': 'IconAddon_looseScrew.png',
    'Останки Ларри': 'IconAddon_larrysRemains.png',
    'Останки Тирана': 'IconAddon_tyrantGore.png',
    'Останки кролика': 'IconAddon_RabbitRemains.png',
    'Остатки лоренцы': 'IconAddon_lorenzasRemains.png',
    'Отвалившаяся ручка': 'IconAddon_looseCrank.png',
    'Отрезанный палец': 'IconAddon_severedToe.png',
    'Отрезанный язык': 'IconAddon_severedTongue.png',
    'Отрубленные руки': 'IconAddon_severedHands.png',
    'Оттомарские записи': 'IconAddon_ottomarianWriting.png',
    'Офисный телефон': 'IconAddon_OfficePhone.png',
    'Охотничий мешок': 'IconAddon_trapperSack.png',
    'Охотничьи перчатки': 'IconAddon_trapperGloves.png',
    'Охотничья сумка': 'IconAddon_trapperBag.png',
    'Очищенная сыворотка': 'IconAddon_refinedSerum.png',
    'Очки Барб': 'IconAddon_barbsGlasses.png',
    'Очки Ридзэ': 'T_UI_iconAddon_RizesGlasses.png',
    'Очки из пиццерии': 'IconAddon_PizzaGoggles.png',
    'Очки матери': 'IconAddon_mothersGlasses.png',
    'Ошейник с шипами': 'IconAddon_spikedCollar.png',
    'Ошейник-электрошокер': 'IconAddon_ElectroshockCollar.png',
    'Ошметок «Уробороса»': 'IconAddon_uroborosTendril.png',
    'Ошметок Малай': 'IconAddon_chunkOfMalai.png',
    'Ошметок Фрэнка': 'IconAddon_sliceOfFrank.png',
    'Панель доступа': 'IconAddon_AccessPanel.png',
    'Паразит NE-A (NE-альфа)': 'IconAddon_ne-AParasite.png',
    'Пахотный инструмент': 'IconAddon_tillingBlade.png',
    'Передовица': 'IconAddon_frontPageArticle.png',
    'Переливающийся снимок': 'IconAddon_iridescentPhotocard.png',
    'Переливчатая Конфигурация Плача': 'IconAddon_iridescentLamentConfiguration.png',
    'Переливчатая бирка Мора': 'IconAddon_iridescentBlightTag.png',
    'Переливчатая плоть': 'IconAddon_iridescentFlesh.png',
    'Переливчатое перо': 'IconAddon_iridescentFeather.png',
    'Переливчатый значок Umbrella': 'IconAddon_iridescentUmbrellaBadge.png',
    'Переливчатый кулон': 'IconAddon_iridescentPendant.png',
    'Переливчатый семейный герб': 'IconAddon_iridescentFamilyCrest.png',
    'Переносной сейф': 'IconAddon_portableSafe.png',
    'Переносной телик': 'IconAddon_portableTv.png',
    'Перо малиновки': 'IconAddon_robinFeather.png',
    'Перо сильфы': 'IconAddon_SylphFeather.png',
    'Перо скворца': 'IconAddon_starlingFeather.png',
    'Перфоратор': 'IconAddon_powerDrill.png',
    'Перчатка Мадлен': 'IconAddon_madeleinesGlove.png',
    'Перчатка Мадо': 'T_UI_iconAddon_MadosGlove.png',
    'Перчатки из оленевой кожи': 'IconAddon_deerskinGloves.png',
    'Петличный микрофон': 'IconAddon_lavalierMicrophone.png',
    'Письмо Аманды': 'IconAddon_amandasLetter.png',
    'Плакат «В розыске»': 'IconAddon_wantedPoster.png',
    'Пластиковый мешок': 'IconAddon_plasticBag.png',
    'Пластырь-бабочка': 'IconAddon_butterflyTape.png',
    'Плащ невидимости': 'IconAddon_CloakOfInvisibility.png',
    'Плетеная безделушка': 'IconAddon_braidedBauble.png',
    'Пломба из песчаника': 'IconAddon_limestoneSeal.png',
    'Поврежденный шприц': 'IconAddon_damagedSyringe.png',
    'Повязка Паркера': 'IconAddon_parkersHeadband.png',
    'Повязки': 'IconAddon_gauzeRoll.png',
    'Погнутое колесо': 'T_UI_iconAddon_BentWheel.png',
    'Погрызенная ручка': 'IconAddon_chewedPen.png',
    'Погрызенный компас': 'IconAddon_gnarledCompass.png',
    'Подаренная бамбуковая расческа': 'IconAddon_giftedBambooComb.png',
    'Поддельное свидетельство о смерти': 'IconAddon_ForgedDeathCertificate.png',
    'Подзорная труба': 'IconAddon_spyglass.png',
    'Подробный план Пилы': 'IconAddon_jigsawsAnnotatedPlan.png',
    'Полевой справочник S.T.A.R.S.': 'IconAddon_starsFieldCombatManual.png',
    'Полицейская рация': 'IconAddon_RPDShoulderWalkie.png',
    'Порванная закладка': 'IconAddon_tornBookmark.png',
    'Порванная занавеска': 'IconAddon_RippedCurtain.png',
    'Порванная книга': 'IconAddon_tornNovel.png',
    'Порванные записи': 'IconAddon_shreddedNotes.png',
    'Порнуха на кассете': 'IconAddon_vhsPorn.png',
    'Порошок гнойника': 'IconAddon_pustulaDust.png',
    'Последние звуки': 'IconAddon_lastKnownRecording.png',
    'Последний вздох «Плохиша»': 'IconAddon_badMansLastBreath.png',
    'Последний вздох Дженнер': 'IconAddon_jennersLastBreath.png',
    'Последний вздох Каваны': 'IconAddon_kavanaghsLastBreath.png',
    'Последний вздох Кэмпбелла': 'IconAddon_campbellsLastBreath.png',
    'Посох увядания': 'IconAddon_StaffOfWithering.png',
    'Потрепанная лента': 'IconAddon_batteredTape.png',
    'Поцарапанная линейка': 'IconAddon_scratchedRuler.png',
    'Поцарапанное зеркало': 'IconAddon_scratchedMirror.png',
    'Праздничная шумелка': 'T_UI_iconAddon_PartyNoisemaker.png',
    'Призыв к оружию': 'IconAddon_callToArms.png',
    'Пробирка с серной кислотой': 'IconAddon_sulphuricAcidVial.png',
    'Провода под напряжением': 'IconAddon_liveWires.png',
    'Производственная смазка': 'IconAddon_shopLubricant.png',
    'Пронзающая проволока': 'IconAddon_impalingWire.png',
    'Пронзенная крыса': 'IconAddon_skeweredRat.png',
    'Пронзительный свист': 'IconAddon_shrillWhistle.png',
    'Пропавший штопор': 'T_UI_iconAddon_MissingCorkscrew.png',
    'Просоленная ткань': 'IconAddon_seaSoakedCloth.png',
    'Проткнутый глаз': 'IconAddon_puncturedEyeball.png',
    'Прототип перчатки с лезвиями': 'IconAddon_prototypeClaws.png',
    'Протравленный клинок': 'IconAddon_treatedBlade.png',
    'Протухшая требуха': 'IconAddon_rottenGreenTripe.png',
    'Процессор Эндо': 'IconAddon_EndoCPU.png',
    'Пружинный зажим': 'IconAddon_springClamp.png',
    'Прядь волос': 'IconAddon_lockOfHair.png',
    'Пузырек для лекарства': 'IconAddon_pillBottle.png',
    'Пульт от видика': 'IconAddon_remoteControl.png',
    'Пурпурная влажноголовка': 'IconAddon_violetWaxcap.png',
    'Пустой кислородный баллон': 'IconAddon_spentOxygenTank.png',
    'Пустой пакет из-под молока': 'IconAddon_discardedMilkCarton.png',
    'Радужная «оболочка»': 'IconAddon_IridescentRemnant.png',
    'Радужная деревянная доска': 'IconAddon_iridescentWoodenPlank.png',
    'Радужная кассета': 'IconAddon_iridescentVideotape.png',
    'Радужная книга гнусной тьмы': 'IconAddon_IridescentBookOfVileDarkness.png',
    'Радужная кнопка': 'IconAddon_iridescentButton.png',
    'Радужная монета': 'IconAddon_iridescentCoin.png',
    'Радужная неопубликованная рукопись': 'IconAddon_iridescentUnpublishedManuscript.png',
    'Радужная печать': 'IconAddon_iridescentSeal.png',
    'Радужная печать Метатрона': 'IconAddon_iridescentSealOfMetatron.png',
    'Радужная повязка на глаз': 'T_UI_iconAddon_iridescentEyePatch.png',
    'Радужная склянка «Уробороса»': 'IconAddon_iridescentUroborosVial.png',
    'Радужное знамя отряда': 'IconAddon_iridescentCompanyBanner.png',
    'Радужное кольцо Влада': 'IconAddon_IridescentRingOfVlad.png',
    'Радужные гравюры': 'IconAddon_iridescentEngravings.png',
    'Радужный амулет': 'IconAddon_iridescentAmulet.png',
    'Радужный доклад УСС': 'IconAddon_iridescentOSSReport.png',
    'Радужный камень': 'IconAddon_iridescentStone.png',
    'Радужный король': 'IconAddon_iridescentKing.png',
    'Радужный лодочный мотор': 'T_UI_iconAddon_IridescentBoatMotor.png',
    'Радужный осколок кристалла': 'IconAddon_iridescentCrystalShard.png',
    'Радужный топор': 'IconAddon_iridescentHead.png',
    'Радужный ферзь': 'IconAddon_iridescentQueen.png',
    'Радужный чип подавления': 'IconAddon_IridescentSoteriaChip.png',
    'Радужный штурвал': 'IconAddon_iridescentWheelHandle.png',
    'Разбитое яйцо черепахи': 'IconAddon_crackedTurtleEgg.png',
    'Разбитый корпус': 'IconAddon_splinteredHull.png',
    'Разводной ключ': 'IconAddon_gripWrench.png',
    'Разгрузочный пояс': 'IconAddon_infantryBelt.png',
    'Разделочный электронож': 'IconAddon_electricCarvingKnife.png',
    'Раздолбанный кассетник': 'IconAddon_SmashedCassetteDeck.png',
    'Размытое фото': 'IconAddon_blurryPhoto.png',
    'Разобранный суперком': 'IconAddon_GuttedSupercom.png',
    'Разованная цепь': 'T_UI_iconAddon_brokenChain.png',
    'Разодранная подушка': 'IconAddon_destroyedPillow.png',
    'Разряженные аккумуляторы': 'IconAddon_expiredBatteries.png',
    'Расколотый вакидзаси': 'IconAddon_shatteredWakizashi.png',
    'Расколотый значок S.T.A.R.S.': 'IconAddon_shatteredSTARSBadge.png',
    'Распорядок дня жертвы': 'IconAddon_victimsDetailedRoutine.png',
    'Растворитель для краски': 'IconAddon_paintThinner.png',
    'Растекшаяся шкурка': 'IconAddon_moultedSkin.png',
    'Расческа для волос': 'IconAddon_hairBrush.png',
    'Расческа матери': 'IconAddon_mothersComb.png',
    'Расширенный прогноз перемещений': 'IconAddon_advancedMovementPrediction.png',
    'Рвотное': 'IconAddon_emeticPotion.png',
    'Реактивное соединение': 'IconAddon_reactiveCompound.png',
    'Режим энергосбережения': 'IconAddon_low-PowerMode.png',
    'Режущая проволока': 'IconAddon_cuttingWire.png',
    'Резиновая рукоятка': 'IconAddon_rubberGrip.png',
    'Резиновые перчатки': 'IconAddon_rubberGloves.png',
    'Рельефный алюминий': 'T_UI_iconAddon_ImprintedAluminum.png',
    'Ремешки': 'IconAddon_cinchStraps.png',
    'Ржавая иголка': 'IconAddon_rustedNeedle.png',
    'Ржавая флейта': 'IconAddon_rustyFlute.png',
    'Ржавая цепь': 'IconAddon_rustedChains.png',
    'Ржавые кандалы': 'IconAddon_rustyShackles.png',
    'Ржавые клыки': 'IconAddon_rustyAttachments.png',
    'Ржавые челюсти': 'IconAddon_rustedJaws.png',
    'Ржавый топор': 'IconAddon_rustyHead.png',
    'Рисунок «Горящий человек»': 'IconAddon_burningManPainting.png',
    'Рисунок кольца': 'IconAddon_ringDrawing.png',
    'Рисунок на стене': 'IconAddon_muralSketch.png',
    'Рисунок фиолетового': 'IconAddon_PurpleGuyDrawing.png',
    'Розовый корень': 'IconAddon_roseRoot.png',
    'Розовый тоник': 'IconAddon_roseTonic.png',
    'Рубиновый венец': 'IconAddon_RubyCirclet.png',
    'Рука Джанджиры': 'IconAddon_janjirasHand.png',
    'Рука андроида': 'IconAddon_androidArm.png',
    'Рука со шрамом': 'IconAddon_scarredHand.png',
    'Руководство': 'IconAddon_instructions.png',
    'Руководство по настройке карбюратора': 'IconAddon_carburettorTuningGuide.png',
    'Рупор': 'IconAddon_bullhorn.png',
    'Ручной культиватор': 'T_UI_iconAddon_GardenClaw.png',
    'Рыцарский договор': 'IconAddon_knightsContract.png',
    'Сад гнили': 'IconAddon_gardenOfRot.png',
    'Садовые грабли': 'IconAddon_gardenRake.png',
    'Сальная черная линза': 'IconAddon_greasyBlackLens.png',
    'Самодельная маска': 'IconAddon_homemadeMask.png',
    'Самодельный бандаж': 'IconAddon_makeshiftWrap.png',
    'Самодельный глушитель': 'IconAddon_homemadeMuffler.png',
    'Самоклеющиеся бинты': 'IconAddon_selfAdherentWrap.png',
    'Самонастраивающийся карбюратор': 'IconAddon_tunedCarburettor.png',
    'Сапоги скорости': 'IconAddon_BootsOfSpeed.png',
    'Сасимоно семьи Ямаока': 'IconAddon_yamaokaSashimono.png',
    'Сая вакидзаси': 'IconAddon_wakizashiSaya.png',
    'Сборник «Предсмертные муки»': 'IconAddon_deathThroesCompilation.png',
    'Свайка': 'IconAddon_marlinspike.png',
    'Свежий кофе': 'T_UI_iconAddon_freshCoffee.png',
    'Сверхмощная батарейка': 'IconAddon_heavyDutyBattery.png',
    'Сверхнапряжение': 'IconAddon_supercharge.png',
    'Светлый волос': 'IconAddon_blondHair.png',
    'Светоотражающий осколок': 'IconAddon_reflectiveFragment.png',
    'Светящаяся смесь': 'IconAddon_glowingConcoction.png',
    'Светящиеся чернила': 'IconAddon_glowingInk.png',
    'Свечка и лак для волос': 'IconAddon_hairSprayCandle.png',
    'Свиной глаз': 'IconAddon_pigsEye.png',
    'Свисток спасателя': 'IconAddon_lifeguardWhistle.png',
    'Сгнившая еда': 'IconAddon_spoiledMeal.png',
    'Сгоревший предохранитель': 'T_UI_iconAddon_BurntFuse.png',
    'Секрет Аманды': 'IconAddon_amandasSecret.png',
    'Семейная фотография Сома': 'IconAddon_somaFamilyPhoto.png',
    'Семиотическая клавиатура': 'IconAddon_semioticKeyboard.png',
    'Сердце Фрэнка': 'IconAddon_franksHeart.png',
    'Сердце зомби': 'IconAddon_zombieHeart.png',
    'Серебряный колокольчик': 'IconAddon_silverBell.png',
    'Сжиженные останки': 'IconAddon_liquifiedGore.png',
    'Сжимной насос': 'IconAddon_primerBulb.png',
    'Сигара Бейшора': 'IconAddon_bayshoresCigar.png',
    'Сила эха': 'IconAddon_ForceOfEcho.png',
    'Сильная микстура': 'IconAddon_potentTincture.png',
    'Сингл «Вижу цель»': 'IconAddon_onTargetSingle.png',
    'Сингл «Сквозь тебя»': 'IconAddon_cutThruUSingle.png',
    'Сияющая брошь': 'IconAddon_shinyPin.png',
    'Скакалка': 'IconAddon_jumpRopePlaytimesOver.png',
    'Скальп с пучком волос': 'IconAddon_scalpedTopknot.png',
    'Скачок - белая краска': 'IconAddon_blink-White.png',
    'Скачок - грязь': 'IconAddon_blink-Mud.png',
    'Скипетр королевы': 'IconAddon_queensScepter.png',
    'Склянка с сывороткой': 'IconAddon_serumVial.png',
    'Скомканные ноты': 'IconAddon_crumpledSheetMusic.png',
    'Скрижаль поклонения': 'IconAddon_worshipTablet.png',
    'Слепой воин - белая краска': 'IconAddon_blindWarrior-White.png',
    'Слепой воин - грязь': 'IconAddon_blindWarrior-Mud.png',
    'Слепок следа': 'IconAddon_footprintCast.png',
    'Сломанная Ракета': 'IconAddon_ShatteredWristRocket.png',
    'Сломанная кукла': 'IconAddon_brokenDoll.png',
    'Сломанная монета восстановления': 'IconAddon_brokenRecoveryCoin.png',
    'Сломанная рукоять': 'IconAddon_brokenHilt.png',
    'Сломанные часы Рин': 'IconAddon_rinsBrokenWatch.png',
    'Сломанный скейт': 'IconAddon_BrokenSkateboard.png',
    'Случайные импульсы': 'IconAddon_randomisedStrobes.png',
    'Слюнявчик Чики': 'IconAddon_ChicasBib.png',
    'Смазка': 'IconAddon_theGrease.png',
    'Смола с изнанки': 'IconAddon_upsideDownResin.png',
    'Смоляная бутылка': 'IconAddon_tarBottle.png',
    'Снаряжение «Часовая башня»': 'IconAddon_ClockTowerGear.png',
    'Сожженные письма': 'IconAddon_burntLetters.png',
    'Солдатик Виктора': 'IconAddon_victorsSoldier.png',
    'Солдатские портянки': 'IconAddon_soldiersPuttee.png',
    'Солдатский шлем': 'IconAddon_warHelmet.png',
    'Солнцезащитные очки': 'IconAddon_Sunglasses.png',
    'Состав №21': 'IconAddon_compoundTwentyOne.png',
    'Состав №33': 'IconAddon_compoundThirtyThree.png',
    'Сосуд с растворителем': 'IconAddon_solventJug.png',
    'Спальный мешок': 'T_UI_iconAddon_SleepingBag.png',
    'Список непослушных': 'IconAddon_mischiefList.png',
    'Список экипажа': 'IconAddon_crewManifest.png',
    'Спичечный коробок': 'IconAddon_matchbox.png',
    'Спичечный коробок из «Судака»': 'IconAddon_walleyesMatchbook.png',
    'Спрей гипервнимательности': 'IconAddon_hyperawarenessSpray.png',
    'Стальные кандалы': 'IconAddon_coldSteelManacles.png',
    'Старые запчасти': 'IconAddon_scraps.png',
    'Стеклянный глаз': 'IconAddon_GlassEye.png',
    'Стереорадиомикрофон': 'IconAddon_stereoRemoteMic.png',
    'Стильные темные очки': 'IconAddon_stylishSunglasses.png',
    'Стойкий парфюм': 'IconAddon_lastingPerfume.png',
    'Стопа манекена': 'IconAddon_mannequinFoot.png',
    'Странная лампочка': 'IconAddon_oddBulb.png',
    'Странное яйцо': 'IconAddon_unknownEgg.png',
    'Стрелки часов': 'IconAddon_ClockHands.png',
    'Стремительная охота - белая краска': 'IconAddon_swiftHunt-White.png',
    'Стремительная охота - грязь': 'IconAddon_swiftHunt-Mud.png',
    'Стремительная охота - кровь': 'IconAddon_swiftHunt-Blood.png',
    'Судорожный вздох': 'IconAddon_spasmodicBreath.png',
    'Сумка с добычей': 'IconAddon_LootBag.png',
    'Сушеная цикада': 'IconAddon_driedCicada.png',
    'Считывание геоданных': 'IconAddon_geographicalReadout.png',
    'Сэндвич Джилл': 'IconAddon_jillsSandwich.png',
    'Сэнко ханаби': 'IconAddon_senkoHanabi.png',
    'Таблетки от сна': 'IconAddon_never-SleepPills.png',
    'Табличка угнетателя': 'IconAddon_tabletOfTheOppressor.png',
    'Тайяки': 'T_UI_iconAddon_taiyaki.png',
    'Талисман Канай Андзэн': 'IconAddon_kanai-AnzenTalisman.png',
    'Талисман каиун': 'IconAddon_kaiunTalisman.png',
    'Танец теней - белая краска': 'IconAddon_shadowDance-White.png',
    'Танец теней - кровь': 'IconAddon_shadowDance-Blood.png',
    'Татуированный средний палец': 'IconAddon_tattoosMiddleFinger.png',
    'Театральный бинокль': 'IconAddon_theaterBinoculars.png',
    'Телеобъектив': 'IconAddon_telephotoLens.png',
    'Телефон': 'IconAddon_telephone.png',
    'Темнейшая тушь': 'IconAddon_darkestInk.png',
    'Темные очки': 'IconAddon_darkSunglasses.png',
    'Теневые соли': 'IconAddon_umbraSalts.png',
    'Токсин медленного действия': 'IconAddon_slow-ReleaseToxin.png',
    'Токсичные отходы': 'T_UI_iconAddon_ToxicWaste.png',
    'Толстая пробка': 'IconAddon_thickCorkStopper.png',
    'Толченое стекло': 'IconAddon_powderedGlass.png',
    'Тонкая нить накаливания': 'IconAddon_lowAmpFilament.png',
    'Точильный камень': 'IconAddon_honingStone.png',
    'Тренировочный колокольчик': 'IconAddon_trainingBell.png',
    'Трюковые ножи': 'IconAddon_trickBlades.png',
    'Тряпичный кляп': 'IconAddon_silencingCloth.png',
    'Туманный день, останки правосудия': 'IconAddon_mistyDay.png',
    'Туфля санитарки': 'T_UI_iconAddon_OrderlysShoe.png',
    'Тюремная цепь': 'IconAddon_prisonChain.png',
    'Увесистая погремушка': 'IconAddon_weightyRattle.png',
    'Угольная палочка': 'IconAddon_charcoalStick.png',
    'Удлиненная челюсть': 'IconAddon_lengthenedJaws.png',
    'Удостоверение CCG': 'T_UI_iconAddon_CCGIDCard.png',
    'Ужасная цепь': 'IconAddon_grislyChains.png',
    'Укол от усталости': 'IconAddon_anti-haemorrhagicSyringe.png',
    'Украденный альбом': 'IconAddon_stolenSketchBook.png',
    'Украшенный рог': 'IconAddon_OrnateHorn.png',
    'Ультразвуковой динамик': 'IconAddon_ultrasonicSpeaker.png',
    'Универсальный топор': 'IconAddon_multipurposeHatchet.png',
    'Уникальное обручальное кольцо': 'IconAddon_uniqueWeddingRing.png',
    'Упавшая дранка': 'IconAddon_fallenShingle.png',
    'Ураган - белая краска': 'IconAddon_windstorm-White.png',
    'Ураган - грязь': 'IconAddon_windstorm-Mud.png',
    'Ураган - кровь': 'IconAddon_windstorm-Blood.png',
    'Устройство видеосвязи': 'IconAddon_videoConferenceDevice.png',
    'Устройство неизвестного назначения': 'IconAddon_deviceOfUndisclosedOrigin.png',
    'Утива': 'IconAddon_uchiwa.png',
    'Утяжеленный топор': 'IconAddon_weightedHead.png',
    'Фаз-монета': 'IconAddon_FazCoin.png',
    'Фартук «Антэйку»': 'T_UI_iconAddon_AnteikuApron.png',
    'Флакон с адреналином': 'IconAddon_adrenalineVial.png',
    'Фокусирующая линза': 'IconAddon_focusLens.png',
    'Фонарь разоблачения': 'IconAddon_LanternOfRevealing.png',
    'Форма заявки с отказом': 'IconAddon_deniedRequisitionForm.png',
    'Фото из лаборатории': 'IconAddon_labPhoto.png',
    'Фотография секты Валтиэля': 'IconAddon_valtielSectPhotograph.png',
    'Фурин': 'IconAddon_furin.png',
    'Хелширское клеймо': 'IconAddon_hellshireIron.png',
    'Хирургическая игла': 'IconAddon_surgicalSuture.png',
    'Хлипкая игрушка': 'IconAddon_ricketyPinwheel.png',
    'Цветные ленты': 'IconAddon_Streamers.png',
    'Цепь от качелей': 'IconAddon_swingChains.png',
    'Цуба катаны': 'IconAddon_katanaTsuba.png',
    'Цыплячья голова': 'IconAddon_chickenHead.png',
    'Часы гипнотизера': 'IconAddon_hypnotistsWatch.png',
    'Часы-реквизит': 'IconAddon_waitingForYouWatch.png',
    'Чаша с кровью': 'IconAddon_BloodFilledGoblet.png',
    'Чашка кинцуги': 'IconAddon_kintsugiTeacup.png',
    'Черная вдова': 'IconAddon_BlackWidowSpider.png',
    'Черная коробка': 'IconAddon_blackBox.png',
    'Чернильное яйцо': 'IconAddon_inkEgg.png',
    'Черный фимиам': 'IconAddon_blackIncense.png',
    'Черствый хлебец': 'IconAddon_staleBiscuit.png',
    'Чешуйчатый лишайник': 'IconAddon_leproseLichen.png',
    'Чили': 'IconAddon_chilli.png',
    'Чили-победитель состязания': 'IconAddon_award-winningChilli.png',
    'Чистая тряпка': 'IconAddon_cleanRag.png',
    'Шарнирный ключ': 'IconAddon_socketSwivels.png',
    'Шарф Мадлен': 'IconAddon_madeleinesScarf.png',
    'Шахматная фигурка': 'IconAddon_ChessPiece.png',
    'Шевелящиеся личинки': 'IconAddon_wrigglingMaggots.png',
    'Шедевр Нэнси': 'IconAddon_nancysMasterpiece.png',
    'Шейное щупальце': 'IconAddon_NeckTendril.png',
    'Шелковая подушка': 'IconAddon_silkPillow.png',
    'Шерстяная рубашка': 'IconAddon_woolShirt.png',
    'Шип язвенника': 'IconAddon_cankerThorn.png',
    'Шипастые лозы': 'IconAddon_thornyVines.png',
    'Шипастые сапоги': 'IconAddon_spikedBoots.png',
    'Шипучка без прикрас': 'IconAddon_fizz-SpinSoda.png',
    'Шлем Кейна': 'IconAddon_kanesHelmet.png',
    'Шляпа Фредди': 'IconAddon_FreddysHat.png',
    'Шляпа путника': 'IconAddon_TravelersHat.png',
    'Шприц с адреналином': 'IconAddon_adrenalineInjector.png',
    'Шприц с серотонином': 'IconAddon_serotoninInjector.png',
    'Шуруповерт': 'IconAddon_automaticScrewdriver.png',
    'Щит Алукарда': 'IconAddon_AlucardsShield.png',
    'Экспериментальный винт': 'IconAddon_prototypeRotor.png',
    'Электролампа': 'IconAddon_powerBulb.png',
    'Эльфийский плащ': 'IconAddon_CloakOfElvenkind.png',
    'Эскиз Нэнси': 'IconAddon_nancysSketch.png',
    'Яблоко праха': 'IconAddon_ashenApple.png',
    'Ядовитая смесь': 'IconAddon_venomousConcoction.png',
    'Язык лизуна': 'IconAddon_lickerTongue.png',
    'Яйцо (золотое)': 'IconAddon_eggGold.png',
    'Яйцо цвета ржавчины': 'IconAddon_rustColoredEgg.png',
    'Яйцо черного козла': 'T_UI_iconAddon_TheBlackGoatsEgg.png',
    'Ячменная мука': 'IconAddon_barleyMeal.png',
    'Ящик с шестеренками': 'IconAddon_crateOfGears.png',
}

SURVIVOR_PORTRAITS = {
    'Ёити Асакава': 'SurvivorYoichi.png',
    'Аврора': 'SurvivorAurora.png',
    'Ада Вонг': 'SurvivorAda.png',
    'Адам Фрэнсис': 'SurvivorAdam.png',
    'Алан Уэйк': 'SurvivorAlan.png',
    'Аэстри Язар': 'SurvivorTroupe.png',
    'Ви Бунясак': 'SurvivorVee.png',
    'Витторио Тоскано': 'SurvivorVittorio.png',
    'Габриэль Сома': 'SurvivorGabriel.png',
    'Дастин Хендерсон': 'SurvivorDustin.png',
    'Детектив Тэпп': 'SurvivorTapp.png',
    'Джейк Парк': 'SurvivorJake.png',
    'Джейн Ромеро': 'SurvivorJane.png',
    'Джефф Йохансен': 'SurvivorJeff.png',
    'Джилл Валентайн': 'SurvivorJill.png',
    'Дуайт Фэйрфилд': 'SurvivorDwight.png',
    'Дэвид Кинг': 'SurvivorDavid.png',
    'Зарина Кассир': 'SurvivorZarina.png',
    'Квентин Смит': 'SurvivorQuentin.png',
    'Квон Тхэён': 'SurvivorKwon.png',
    'Кейт Денсон': 'SurvivorKate.png',
    'Клодетт Морель': 'SurvivorClaudette.png',
    'Лара Крофт': 'SurvivorLara.png',
    'Леон С. Кеннеди': 'SurvivorLeon.png',
    'Ли Юнчин': 'SurvivorYun-Jin.png',
    'Лори Строуд': 'SurvivorLaurie.png',
    'Микаэла Рид': 'SurvivorMikaela.png',
    'Мишон Граймс': 'SurvivorMichonne.png',
    'Мэг Томас': 'SurvivorMeg.png',
    'Нея Карлссон': 'SurvivorNea.png',
    'Николас Кейдж': 'SurvivorNicolas.png',
    'Нэнси Уиллер': 'SurvivorNancy.png',
    'Одиннадцать': 'SurvivorEleven.png',
    'Орела Роуз': 'SurvivorOrela.png',
    'Ребекка Чемберс': 'SurvivorRebecca.png',
    'Ренато Лира': 'SurvivorRenato.png',
    'Рик Граймс': 'SurvivorRick.png',
    'Сейбл Уорд': 'SurvivorSable.png',
    'Стив Харрингтон': 'SurvivorSteve.png',
    'Талита Лира': 'SurvivorThalita.png',
    'Тори Кейн': 'SurvivorTaurie.png',
    'Тревор Бельмонт': 'SurvivorTrevor.png',
    'Уильям Овербек': 'SurvivorBill.png',
    'Феликс Рихтер': 'SurvivorFelix.png',
    'Фенг Мин': 'SurvivorFeng.png',
    'Хонас Васкес': 'SurvivorJonah.png',
    'Хэдди Каур': 'SurvivorHaddie.png',
    'Шейн Уиигваас': 'SurvivorShane.png',
    'Шерил Мейсон': 'SurvivorCheryl.png',
    'Эйс Висконти': 'SurvivorAce.png',
    'Эллен Рипли': 'SurvivorEllen.png',
    'Элоди Ракото': 'SurvivorElodie.png',
    'Эшли Уильямс': 'SurvivorAsh.png',
    'Юи Кимура': 'SurvivorYui.png',
}

KILLER_PORTRAITS = {
    'Аниматроник': 'K40_TheAnimatronic_Portrait.png',
    'Гуль': 'K39_TheGhoul_Portrait.png',
    'Егерь': 'K38_TheHoundmaster_Portrait.png',
    'Красу': 'K41_TheKrasue_Portrait.png',
    'Первый': 'K42_TheFirst_Portrait.png',
    'Правосудие': 'K44_TheJudgment_Portrait.png',
    'Слэшер': 'K43_TheSlasher_Portrait.png',
}

POWER_ICONS = {
    'UVX': 'IconPowers_uvx.png',
    'Бензопила': 'IconPowers_chainsaw.png',
    'Бензопила Буббы': 'IconPowers_bubbasChainsaw.png',
    'Вездесущее зло': 'T_UI_iconPowers_DramaticEntrance.png',
    'Воля богов': 'T_UI_iconPowers_ChargeRay.png',
    'Глаза в небесах': 'IconPowers_eyesInTheSky.png',
    'Гнев Ямаоки': 'IconPowers_yamaokasWrath.png',
    'Гнусная тьма': 'IconPowers_VileDarkness.png',
    'Демон снов': 'IconPowers_dreamDemon.png',
    'Дикое бешенство': 'IconPowers_feralFrenzy.png',
    'Добивающий тоник': 'IconPowers_gasBomb.png',
    'Запах крови': 'IconPowers_K38_dashCommand.png',
    'Заразный порыв': 'IconPowers_virulentBound.png',
    'Зов боли': 'IconPowers_summonsOfPain.png',
    'Игры кончились': 'IconPowers_playtimesOver.png',
    'Из бездны': 'IconPowers_ofTheAbyss.png',
    'Искра Картера': 'IconPowers_cartersSpark.png',
    'Искупитель': 'IconPowers_theRedeemer.png',
    'Квантовая реализация': 'IconPowers_quantumInstantiation.png',
    'Коронный номер': 'IconPowers_showstopper.png',
    'Медвежий капкан': 'IconPowers_trap.png',
    'Моровая скверна': 'IconPowers_blightedCorruption.png',
    'Ночной саван': 'IconPowers_nightShroud.png',
    'Облики вампира': 'IconPowers_K37_Shapeshift.png',
    'Обратный медвежий капкан': 'IconPowers_jigsawsBaptism.png',
    'Обряды осуждения': 'IconPowers_ritesOfJudgement.png',
    'Отряд Гуардия': 'IconPowers_guardiaCompagnia.png',
    'Охотничьи топоры': 'IconPowers_huntingHatchets.png',
    'Очищение от мерзости': 'IconPowers_vilePurge.png',
    'Плачущий колокол': 'IconPowers_bell.png',
    'Подопытный 001': 'T_UI_iconPowers_EnterUpsideDown.png',
    'Последнее дыхание Спенсера': 'IconPowers_breath.png',
    'Преследование Ямаоки': 'IconPowers_yamaokasHaunting.png',
    'Проклятая грязь': 'IconPowers_blackenedCatalyst.png',
    'Скрытная погоня': 'IconPowers_hiddenPursuit.png',
    'Т-вирус': 'IconPowers_t-Virus.png',
    'Терзающие птицы': 'IconPowers_birdsOfTorment.png',
    'Узы крови': 'IconPowers_bloodBond.png',
    'Царство мрака': 'IconPowers_reignOfDarkness.png',
    'Чистое зло': 'T_UI_iconPowers_evilWithin.png',
    'Шквал ужаса': 'IconPowers_delugeOfFear.png',
}

ITEM_ICONS = {
    'Аптечка': 'IconItems_firstAidKit.png',
    'Аптечка годовщины': 'IconItems_anniversaryMedKit.png',
    'Аптечка лесничего': 'IconItems_rangerMedKit.png',
    'Аптечка первой помощи': 'IconItems_firstAidKit.png',
    'Банкетная аптечка': 'T_UI_iconItems_medkit_anniversary2026.png',
    'Банкетный фонарик': 'T_UI_iconItems_flashlight_anniversary2026.png',
    'Банкетный ящик с инструментами': 'T_UI_iconItems_toolbox_anniversary2026.png',
    'Блуждающий огонек': 'IconItems_willOWisp.png',
    'Вместительный ящик с инструментами': 'IconItems_commodiousToolbox.png',
    'Загадочная карта': 'IconItems_CrypticMap.png',
    'Изношенные инструменты': 'IconItems_wornOutTools.png',
    'Инструменты Алекса': 'IconItems_alexsToolbox.png',
    'Инструменты инженера': 'IconItems_engineersToolbox.png',
    'Инструменты механика': 'IconItems_mechanicsToolbox.png',
    'Карта кровавого чувства': 'IconItems_bloodsenseMap.png',
    'Китайская хлопушка': 'IconItems_chineseFirecracker.png',
    'Ключ скелета': 'IconItems_skeletonKey.png',
    'Ланчбокс всех святых': 'IconItems_allHallowsEveLunchbox.png',
    'Маскарадная аптечка': 'IconItems_masqueradeMedKit.png',
    'Маскарадный фонарик': 'IconItems_masqueradeFlashlight.png',
    'Маскарадный ящик с инструментами': 'IconItems_masqueradeToolbox.png',
    'Новогодняя хлопушка': 'IconItems_winterPartyStarter.png',
    'Потертый ключ': 'IconItems_dullKey.png',
    'Походная аптечка': 'IconItems_campingAidKit.png',
    'Праздничный ящик с инструментами': 'IconItems_festiveToolbox.png',
    'Сломанный ключ': 'IconItems_brokenKey.png',
    'Спортивный фонарик': 'IconItems_sportFlashlight.png',
    'Туманный кристалл': 'IconItems_calamariSmokeBomb.png',
    'Тяжелый фонарь': 'IconItems_utilityFlashlight.png',
    'Флакон Виго с туманом': 'IconItems_vigosFogVial.png',
    'Флакон мастерового с туманом': 'IconItems_artisansFogVial.png',
    'Флакон подмастерья с туманом': 'IconItems_apprenticesFogVial.png',
    'Фонарик': 'IconItems_flashlight.png',
    'Фонарик годовщины': 'IconItems_anniversaryFlashlight.png',
    'Хлопушка третьей годовщины': 'IconItems_thirdYearPartyStarter.png',
    'Юбилейный ящик с инструментами': 'IconItems_anniversaryToolbox.png',
    'Ящик с инструментами': 'IconItems_toolbox.png',
}

KILLER_SPRITE = {
    'url': 'https://deadbydaylight.wiki.gg/images/KillerPortraitsSprite.png',
    'size': 512,
    'cols': 10,
    'ports': {
        'Близнецы': 23,
        'Ведьма': 6,
        'Гоуст Фейс': 17,
        'Грязь': 29,
        'Демогоргон': 18,
        'Деревенщина': 4,
        'Доктор': 8,
        'Дух': 14,
        'Каннибал': 10,
        'Клоун': 13,
        'Кошмар': 11,
        'Ксеноморф': 34,
        'Кукловод': 30,
        'Легион': 15,
        'Лич': 37,
        'Медсестра': 5,
        'Мор': 22,
        'Неведомое': 36,
        'Немезис': 25,
        'Они': 19,
        'Онрё': 28,
        'Охотник': 2,
        'Охотница': 9,
        'Палач': 21,
        'Призрак': 3,
        'Рыцарь': 31,
        'Свинья': 12,
        'Сенобит': 26,
        'Сингулярность': 33,
        'Стрелок': 20,
        'Тень': 7,
        'Торговка черепами': 32,
        'Трюкач': 24,
        'Тёмный властелин': 38,
        'Хороший парень': 35,
        'Художница': 27,
        'Чума': 16,
    },
}
