# -*- coding: utf-8 -*-
"""Сгенерировано tools/resolve_skins.py — НЕ править вручную.

Наборы одежды (скины): id -> данные + файл превью на wiki.gg.
Имена английские: RU-названий нет в открытых данных (v1), картинка
позволяет найти набор в русском клиенте. Ключи стабильны (id).
"""

SKIN_BASE = "https://deadbydaylight.wiki.gg/images/"

SKINS_BY_ID = {
    1: {'name': 'Look-See', 'char': 'Доктор', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC001_charSelect_portrait.png'},
    2: {'name': 'Birch', 'char': 'Тень', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': 'CC002_charSelect_portrait.png'},
    3: {'name': 'Mordeo', 'char': 'Охотница', 'side': 'KILLER', 'rarity': 12, 'rarity_ru': '', 'file': 'CC003_charSelect_portrait.png'},
    4: {'name': 'Krampus', 'char': 'Охотник', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC004_charSelect_portrait.png'},
    5: {'name': 'Minotaur', 'char': 'Они', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC005_charSelect_portrait.png'},
    6: {'name': 'Ferryman', 'char': 'Мор', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC006_charSelect_portrait.png'},
    7: {'name': 'Chatterer', 'char': 'Сенобит', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC007_charSelect_portrait.png'},
    8: {'name': 'Baba Yaga', 'char': 'Охотница', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC008_charSelect_portrait.png'},
    9: {'name': 'Lisa Garland', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC009_charSelect_portrait.png'},
    10: {'name': 'Cybil Bennett', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC010_charSelect_portrait.png'},
    11: {'name': 'James Sunderland', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC011_charSelect_portrait.png'},
    12: {'name': 'Alessa Gillespie', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC012_charSelect_portrait.png'},
    13: {'name': 'Jonathan Byers', 'char': 'Нэнси Уиллер', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC013_charSelect_portrait.png'},
    14: {'name': 'Claire Redfield', 'char': 'Джилл Валентайн', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC014_charSelect_portrait.png'},
    16: {'name': 'God of Desire', 'char': 'Трюкач', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC016_charSelect_portrait.png'},
    17: {'name': 'Rotten Remains', 'char': 'Онрё', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC017_charSelect_portrait.png'},
    18: {'name': 'Armoured Titan', 'char': 'Они', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC018_charSelect_portrait.png'},
    19: {'name': 'War Hammer Titan', 'char': 'Дух', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC019_charSelect_portrait.png'},
    20: {'name': 'HUNK', 'char': 'Легион', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC020_charSelect_portrait.png'},
    21: {'name': 'William Birkin', 'char': 'Мор', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC021_charSelect_portrait.png'},
    22: {'name': 'Jabberwock', 'char': 'Художница', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC022_charSelect_portrait.png'},
    23: {'name': 'Maria', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC023_charSelect_portrait.png'},
    24: {'name': 'Draugr', 'char': 'Рыцарь', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC024_charSelect_portrait.png'},
    25: {'name': 'Xenomorph Queen', 'char': 'Ксеноморф', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC025_charSelect_portrait.png'},
    26: {'name': 'Xenomorph Clone', 'char': 'Ксеноморф', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': 'CC026_charSelect_portrait.png'},
    27: {'name': 'Grid Xenomorph', 'char': 'Ксеноморф', 'side': 'KILLER', 'rarity': 3, 'rarity_ru': '', 'file': 'CC027_charSelect_portrait.png'},
    28: {'name': 'Naughty Bear', 'char': 'Охотник', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC028_charSelect_portrait.png'},
    29: {'name': 'Good Gal', 'char': 'Хороший парень', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC029_charSelect_portrait.png'},
    30: {'name': 'Pharaoh Eddie', 'char': 'Доктор', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC030_charSelect_portrait.png'},
    31: {'name': 'Stranger Eddie', 'char': 'Стрелок', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC031_charSelect_portrait.png'},
    32: {'name': "Eddie's Tribute", 'char': 'Грязь', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC032_charSelect_portrait.png'},
    33: {'name': 'Samurai Eddie', 'char': 'Они', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC033_charSelect_portrait.png'},
    34: {'name': 'Were-Elk', 'char': 'Охотница', 'side': 'KILLER', 'rarity': 5, 'rarity_ru': '', 'file': 'CC034_charSelect_portrait.png'},
    35: {'name': 'Tubarão', 'char': 'Ренато Лира', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC035_charSelect_portrait.png'},
    36: {'name': 'Blitz', 'char': 'Феликс Рихтер', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC036_charSelect_portrait.png'},
    37: {'name': 'Wamai', 'char': 'Адам Фрэнсис', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC037_charSelect_portrait.png'},
    38: {'name': 'Annie Leonhart', 'char': 'Мэг Томас', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC038_charSelect_portrait.png'},
    39: {'name': 'Armin Arlert', 'char': 'Феликс Рихтер', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC039_charSelect_portrait.png'},
    40: {'name': 'Eren Yeager', 'char': 'Дуайт Фэйрфилд', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC040_charSelect_portrait.png'},
    41: {'name': 'Hange Zoë', 'char': 'Зарина Кассир', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC041_charSelect_portrait.png'},
    42: {'name': 'Historia Reiss', 'char': 'Кейт Денсон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC042_charSelect_portrait.png'},
    43: {'name': 'Kenny Ackerman', 'char': 'Эйс Висконти', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC043_charSelect_portrait.png'},
    44: {'name': 'Levi Ackerman', 'char': 'Джейк Парк', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC044_charSelect_portrait.png'},
    45: {'name': 'Mikasa Ackerman', 'char': 'Юи Кимура', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC045_charSelect_portrait.png'},
    46: {'name': 'Ripley 8', 'char': 'Эллен Рипли', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC046_charSelect_portrait.png'},
    47: {'name': 'Saga Anderson', 'char': 'Алан Уэйк', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC047_charSelect_portrait.png'},
    48: {'name': 'Rose Marigold', 'char': 'Алан Уэйк', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC048_charSelect_portrait.png'},
    49: {'name': 'Mr Scratch', 'char': 'Алан Уэйк', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC049_charSelect_portrait.png'},
    51: {'name': 'Sheva Alomar', 'char': 'Джилл Валентайн', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC051_charSelect_portrait.png'},
    52: {'name': 'Rain Carradine', 'char': 'Эллен Рипли', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC052_charSelect_portrait.png'},
    53: {'name': 'Alucard', 'char': 'Тревор Бельмонт', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC053_charSelect_portrait.png'},
    54: {'name': 'Soma Cruz', 'char': 'Тревор Бельмонт', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC054_charSelect_portrait.png'},
    55: {'name': 'True Form', 'char': 'Тёмный властелин', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC055_charSelect_portrait.png'},
    56: {'name': 'Miss Fuchi', 'char': 'Художница', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC056_charSelect_portrait.png'},
    57: {'name': 'Tomie Kawakami', 'char': 'Дух', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC057_charSelect_portrait.png'},
    58: {'name': "Half Spirits' Torments", 'char': 'Грязь', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC058_charSelect_portrait.png'},
    59: {'name': 'Rize Kamishiro', 'char': 'Гуль', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC059_charSelect_portrait.png'},
    60: {'name': 'Geralt of Rivia', 'char': 'Витторио Тоскано', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC060_charSelect_portrait.png'},
    61: {'name': 'Leshen', 'char': 'Художница', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC061_charSelect_portrait.png'},
    62: {'name': 'Yellow Rabbit', 'char': 'Аниматроник', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC062_charSelect_portrait.png'},
    63: {'name': 'Glitchtrap', 'char': 'Аниматроник', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC063_charSelect_portrait.png'},
    64: {'name': 'Boulet Artist', 'char': 'Художница', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC064_charSelect_portrait.png'},
    66: {'name': 'Murderous Grizzly', 'char': 'Они', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC066_charSelect_portrait.png'},
    68: {'name': 'Richter Belmont', 'char': 'Тревор Бельмонт', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC068_charSelect_portrait.png'},
    70: {'name': 'Robin Buckley', 'char': 'Нэнси Уиллер', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC070_charSelect_portrait.png'},
    71: {'name': 'Leon Belmont', 'char': 'Тревор Бельмонт', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    72: {'name': 'Simon Belmont', 'char': 'Тревор Бельмонт', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    73: {'name': 'Maria Renard', 'char': 'Кейт Денсон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    74: {'name': 'Sypha Belnades', 'char': 'Микаэла Рид', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    75: {'name': 'Jonathan Morris', 'char': 'Феликс Рихтер', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    76: {'name': 'Shanoa', 'char': 'Юи Кимура', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    77: {'name': 'Death', 'char': 'Медсестра', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    78: {'name': 'Souichi Tsujii', 'char': 'Трюкач', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    79: {'name': 'Kinkao & Minkao Hikizuri', 'char': 'Близнецы', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    80: {'name': 'Terumi Fujino', 'char': 'Ли Юнчин', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    81: {'name': 'Marionette', 'char': 'Кейт Денсон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    82: {'name': 'Tsukiko Izumisawa', 'char': 'Юи Кимура', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    83: {'name': 'Hideyoshi Nagachika', 'char': 'Ренато Лира', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    84: {'name': 'Eto Yoshimura', 'char': 'Нея Карлссон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    85: {'name': 'Touka Kirishima', 'char': 'Юи Кимура', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    86: {'name': 'Yennefer of Vengerberg', 'char': 'Кейт Денсон', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC086_charSelect_portrait.png'},
    87: {'name': 'Ciri', 'char': 'Сейбл Уорд', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC087_charSelect_portrait.png'},
    88: {'name': 'Triss Merigold', 'char': 'Микаэла Рид', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    89: {'name': 'Eredin Bréacc Glas', 'char': 'Рыцарь', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    90: {'name': 'Winter Warrior', 'char': 'Охотница', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    91: {'name': 'Kaoru', 'char': 'Юи Кимура', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    92: {'name': 'Robbie The Rabbit', 'char': 'Легион', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': None},
    93: {'name': 'One', 'char': 'Первый', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC093_charSelect_portrait.png'},
    94: {'name': 'MiNA', 'char': 'Трюкач', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC094_charSelect_portrait.png'},
    95: {'name': 'William Hudson', 'char': 'Эллен Рипли', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC095_charSelect_portrait.png'},
    96: {'name': 'Attack Titan', 'char': 'Охотник', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC096_charSelect_portrait.png'},
    97: {'name': 'Sasha Braus', 'char': 'Талита Лира', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC097_charSelect_portrait.png'},
    98: {'name': 'Collector', 'char': 'Медсестра', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': 'CC098_charSelect_portrait.png'},
    99: {'name': 'Hellion', 'char': 'Мэг Томас', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC099_charSelect_portrait.png'},
    100: {'name': 'Highwayman', 'char': 'Дэвид Кинг', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC100_charSelect_portrait.png'},
    101: {'name': 'Leper', 'char': 'Витторио Тоскано', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC101_charSelect_portrait.png'},
    102: {'name': 'Plague Doctor', 'char': 'Зарина Кассир', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': 'CC102_charSelect_portrait.png'},
    103: {'name': 'Prophet', 'char': 'Мор', 'side': 'KILLER', 'rarity': 4, 'rarity_ru': '', 'file': 'CC103_charSelect_portrait.png'},
    104: {'name': 'Shimizu Hinako', 'char': 'Шерил Мейсон', 'side': 'SURVIVOR', 'rarity': 7, 'rarity_ru': '', 'file': 'CC104_charSelect_portrait.png'},
    105: {'name': 'Facemelter Eddie', 'char': 'Охотница', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC105_charSelect_portrait.png'},
    107: {'name': 'Xenomorph King', 'char': 'Ксеноморф', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': 'CC107_charSelect_portrait.png'},
    108: {'name': 'Lilith', 'char': 'Гоуст Фейс', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': None},
    109: {'name': 'Scooby-Doo', 'char': 'Дуайт Фэйрфилд', 'side': 'SURVIVOR', 'rarity': 4, 'rarity_ru': '', 'file': None},
    111: {'name': 'Bubble Head Nurse', 'char': 'Дух', 'side': 'KILLER', 'rarity': 7, 'rarity_ru': '', 'file': None},
}

CHAR_SKINS = {
    'Адам Фрэнсис': [37],
    'Алан Уэйк': [47, 48, 49],
    'Аниматроник': [62, 63],
    'Близнецы': [79],
    'Витторио Тоскано': [60, 101],
    'Гоуст Фейс': [108],
    'Грязь': [32, 58],
    'Гуль': [59],
    'Джейк Парк': [44],
    'Джилл Валентайн': [14, 51],
    'Доктор': [1, 30],
    'Дуайт Фэйрфилд': [40, 109],
    'Дух': [19, 57, 111],
    'Дэвид Кинг': [100],
    'Зарина Кассир': [41, 102],
    'Кейт Денсон': [42, 73, 81, 86],
    'Ксеноморф': [25, 26, 27, 107],
    'Легион': [20, 92],
    'Ли Юнчин': [80],
    'Медсестра': [77, 98],
    'Микаэла Рид': [74, 88],
    'Мор': [6, 21, 103],
    'Мэг Томас': [38, 99],
    'Нея Карлссон': [84],
    'Нэнси Уиллер': [13, 70],
    'Они': [5, 18, 33, 66],
    'Онрё': [17],
    'Охотник': [4, 28, 96],
    'Охотница': [3, 8, 34, 90, 105],
    'Первый': [93],
    'Ренато Лира': [35, 83],
    'Рыцарь': [24, 89],
    'Сейбл Уорд': [87],
    'Сенобит': [7],
    'Стрелок': [31],
    'Талита Лира': [97],
    'Тень': [2],
    'Тревор Бельмонт': [53, 54, 68, 71, 72],
    'Трюкач': [16, 78, 94],
    'Тёмный властелин': [55],
    'Феликс Рихтер': [36, 39, 75],
    'Хороший парень': [29],
    'Художница': [22, 56, 61, 64],
    'Шерил Мейсон': [9, 10, 11, 12, 23, 104],
    'Эйс Висконти': [43],
    'Эллен Рипли': [46, 52, 95],
    'Юи Кимура': [45, 76, 82, 85, 91],
}

# ключи вида 'skin:<id>' — для общего IconStore
SKIN_FILES = {
    'skin:1': 'CC001_charSelect_portrait.png',
    'skin:2': 'CC002_charSelect_portrait.png',
    'skin:3': 'CC003_charSelect_portrait.png',
    'skin:4': 'CC004_charSelect_portrait.png',
    'skin:5': 'CC005_charSelect_portrait.png',
    'skin:6': 'CC006_charSelect_portrait.png',
    'skin:7': 'CC007_charSelect_portrait.png',
    'skin:8': 'CC008_charSelect_portrait.png',
    'skin:9': 'CC009_charSelect_portrait.png',
    'skin:10': 'CC010_charSelect_portrait.png',
    'skin:11': 'CC011_charSelect_portrait.png',
    'skin:12': 'CC012_charSelect_portrait.png',
    'skin:13': 'CC013_charSelect_portrait.png',
    'skin:14': 'CC014_charSelect_portrait.png',
    'skin:16': 'CC016_charSelect_portrait.png',
    'skin:17': 'CC017_charSelect_portrait.png',
    'skin:18': 'CC018_charSelect_portrait.png',
    'skin:19': 'CC019_charSelect_portrait.png',
    'skin:20': 'CC020_charSelect_portrait.png',
    'skin:21': 'CC021_charSelect_portrait.png',
    'skin:22': 'CC022_charSelect_portrait.png',
    'skin:23': 'CC023_charSelect_portrait.png',
    'skin:24': 'CC024_charSelect_portrait.png',
    'skin:25': 'CC025_charSelect_portrait.png',
    'skin:26': 'CC026_charSelect_portrait.png',
    'skin:27': 'CC027_charSelect_portrait.png',
    'skin:28': 'CC028_charSelect_portrait.png',
    'skin:29': 'CC029_charSelect_portrait.png',
    'skin:30': 'CC030_charSelect_portrait.png',
    'skin:31': 'CC031_charSelect_portrait.png',
    'skin:32': 'CC032_charSelect_portrait.png',
    'skin:33': 'CC033_charSelect_portrait.png',
    'skin:34': 'CC034_charSelect_portrait.png',
    'skin:35': 'CC035_charSelect_portrait.png',
    'skin:36': 'CC036_charSelect_portrait.png',
    'skin:37': 'CC037_charSelect_portrait.png',
    'skin:38': 'CC038_charSelect_portrait.png',
    'skin:39': 'CC039_charSelect_portrait.png',
    'skin:40': 'CC040_charSelect_portrait.png',
    'skin:41': 'CC041_charSelect_portrait.png',
    'skin:42': 'CC042_charSelect_portrait.png',
    'skin:43': 'CC043_charSelect_portrait.png',
    'skin:44': 'CC044_charSelect_portrait.png',
    'skin:45': 'CC045_charSelect_portrait.png',
    'skin:46': 'CC046_charSelect_portrait.png',
    'skin:47': 'CC047_charSelect_portrait.png',
    'skin:48': 'CC048_charSelect_portrait.png',
    'skin:49': 'CC049_charSelect_portrait.png',
    'skin:51': 'CC051_charSelect_portrait.png',
    'skin:52': 'CC052_charSelect_portrait.png',
    'skin:53': 'CC053_charSelect_portrait.png',
    'skin:54': 'CC054_charSelect_portrait.png',
    'skin:55': 'CC055_charSelect_portrait.png',
    'skin:56': 'CC056_charSelect_portrait.png',
    'skin:57': 'CC057_charSelect_portrait.png',
    'skin:58': 'CC058_charSelect_portrait.png',
    'skin:59': 'CC059_charSelect_portrait.png',
    'skin:60': 'CC060_charSelect_portrait.png',
    'skin:61': 'CC061_charSelect_portrait.png',
    'skin:62': 'CC062_charSelect_portrait.png',
    'skin:63': 'CC063_charSelect_portrait.png',
    'skin:64': 'CC064_charSelect_portrait.png',
    'skin:66': 'CC066_charSelect_portrait.png',
    'skin:68': 'CC068_charSelect_portrait.png',
    'skin:70': 'CC070_charSelect_portrait.png',
    'skin:86': 'CC086_charSelect_portrait.png',
    'skin:87': 'CC087_charSelect_portrait.png',
    'skin:93': 'CC093_charSelect_portrait.png',
    'skin:94': 'CC094_charSelect_portrait.png',
    'skin:95': 'CC095_charSelect_portrait.png',
    'skin:96': 'CC096_charSelect_portrait.png',
    'skin:97': 'CC097_charSelect_portrait.png',
    'skin:98': 'CC098_charSelect_portrait.png',
    'skin:99': 'CC099_charSelect_portrait.png',
    'skin:100': 'CC100_charSelect_portrait.png',
    'skin:101': 'CC101_charSelect_portrait.png',
    'skin:102': 'CC102_charSelect_portrait.png',
    'skin:103': 'CC103_charSelect_portrait.png',
    'skin:104': 'CC104_charSelect_portrait.png',
    'skin:105': 'CC105_charSelect_portrait.png',
    'skin:107': 'CC107_charSelect_portrait.png',
}
