# -*- coding: utf-8 -*-
"""Сгенерировано tools/resolve_icons.py — НЕ править вручную.

Русское имя навыка -> прямой URL иконки на deadbydaylight.wiki.gg.
Иконки НЕ лежат в репозитории: приложение качает их по мере надобности
и кэширует локально (см. IconStore в dbd_icons_store.py).
"""

ICON_BASE = "https://deadbydaylight.wiki.gg/images/"

PERK_ICONS = {
    'Аварийная кнопка': 'IconPerks_deadMansSwitch.png',
    'Адреналин': 'IconPerks_adrenaline.png',
    'Алчность': 'IconPerks_HumanGreed.png',
    'Апокалиптическая смекалка': 'IconPerks_apocalypticIngenuity.png',
    'Аптекарь': 'IconPerks_pharmacy.png',
    'Бада-бада-бум': 'IconsPerks_BadaBadaBoom.png',
    'Барбекю и чили': 'IconPerks_barbecueAndChilli.png',
    'Батарейки в комплекте': 'IconPerks_batteriesIncluded.png',
    'Бац!': 'IconPerks_thwack.png',
    'Без огласки': 'IconPerks_offTheRecord.png',
    'Без пощады': 'IconPerks_noQuarter.png',
    'Без сожаления': 'IconPerks_noMither.png',
    'Безжалостный': 'IconPerks_unrelenting.png',
    'Безжалостный шторм': 'IconPerks_mercilessStorm.png',
    'Безжизненное касание': 'IconPerks_languidTouch.png',
    'Безмолвная тень': 'T_UI_iconsPerks_SilentShadow.png',
    'Безумное упорство': 'IconPerks_madGrit.png',
    'Бессонница': 'IconPerks_vigil.png',
    'Блуждающий взгляд': 'IconPerks_WanderingEye.png',
    'Бремя на себя': 'IconPerks_shoulderTheBurden.png',
    'Быстрая жестокость': 'IconPerks_rapidBrutality.png',
    'Быстрое реагирование': 'IconsPerks_RapidResponse.png',
    'Быстрый гамбит': 'IconPerks_quickGambit.png',
    'Быстрый и тихий': 'IconPerks_quickAndQuiet.png',
    'Вдохновение барда': 'IconPerks_bardicInspiration.png',
    'Везение': 'IconPerks_luckyBreak.png',
    'Визионер': 'IconPerks_visionary.png',
    'Владычество': 'IconPerks_Dominance.png',
    'Вмешательство скверны': 'IconPerks_corruptIntervention.png',
    'Внутренняя сила': 'IconPerks_innerStrength.png',
    'Возмездие': 'IconPerks_nemesis.png',
    'Воин света': 'IconPerks_championOfLight.png',
    'Восприятие экстрасенса': 'IconsPerks_ExtrasensoryPerception.png',
    'Вот это поворот': 'IconPerks_plotTwist.png',
    'Врачебный долг': 'IconsPerks_DutyOfCare.png',
    'Все несвободны': 'IconPerks_NoneAreFree.png',
    'Второе дыхание': 'IconPerks_secondWind.png',
    'Выбор за тобой': 'IconPerks_makeYourChoice.png',
    'Выброс': 'IconPerks_surge.png',
    'Выдержка': 'IconPerks_tenacity.png',
    'Вынужденная нерешительность': 'IconPerks_forcedHesitation.png',
    'Выслеживание подозреваемого': 'IconPerks_stakeOut.png',
    'Выхода нет': 'IconPerks_noWayOut.png',
    'Выше головы': 'IconPerks_bloodRush.png',
    'Генетические ограничения': 'IconPerks_geneticLimits.png',
    'Гибель Франклина': 'IconPerks_franklinsDemise.png',
    'Гибкость': 'IconPerks_lithe.png',
    'Глаза Бельмонта': 'IconPerks_EyesOfBelmont.png',
    'Голод': 'IconPerks_Ravenous.png',
    'Городской бег': 'IconPerks_urbanEvasion.png',
    'Дар: круг исцеления': 'IconPerks_boonCircleOfHealing.png',
    'Дар: непоколебимость': 'T_UI_iconsPerks_BoonSteadfast.png',
    'Дар: освещение': 'IconPerks_boonIllumination.png',
    'Дар: теория мрака': 'IconPerks_boonDarkTheory.png',
    'Дар: уход в тень': 'IconPerks_boonShadowStep.png',
    'Дар: экспонента': 'IconPerks_boonExponential.png',
    'Дедлайн': 'IconPerks_deadline.png',
    'Дежавю': 'IconPerks_dejaVu.png',
    'Дерзость': 'IconPerks_wicked.png',
    'Детективное чутье': 'IconPerks_detectivesHunch.png',
    'Детище света': 'IconPerks_lightborn.png',
    'Детище тьмы': 'IconPerks_shadowborn.png',
    'Диверсия': 'IconPerks_diversion.png',
    'Добивание': 'IconPerks_coupDeGr%C3%A2ce.png',
    'Догонялки': 'IconPerks_gameAfoot.png',
    'Драконья хватка': 'IconPerks_dragonsGrip.png',
    'Драматургия': 'IconPerks_dramaturgy.png',
    'Дружеское состязание': 'IconPerks_friendlyCompetition.png',
    'Друзья до гроба': 'IconPerks_friendsTilTheEnd.png',
    'Дух новичка': 'IconPerks_rookieSpirit.png',
    'Единственный выживший': 'IconPerks_soleSurvivor.png',
    'Железная воля': 'IconPerks_ironWill.png',
    'Железная дева': 'IconPerks_ironMaiden.png',
    'Жестокая изоляция': 'IconPerks_cruelLimits.png',
    'Жизнь в дороге': 'IconPerks_RoadLife.png',
    'Жучок': 'IconPerks_wiretap.png',
    'За чужой счет': 'IconPerks_fastTrack.png',
    'Закалка': 'IconPerks_hardened.png',
    'Замри и увидишь': 'IconPerks_stillSight.png',
    'Запасной игрок': 'IconPerks_backgroundPlayer.png',
    'Записки о призраке': 'IconPerks_GhostNotes.png',
    'Заразительный ужас': 'IconPerks_infectiousFright.png',
    'Зверская сила': 'IconPerks_brutalStrength.png',
    'Зеркальная иллюзия': 'IconPerks_mirroredIllusion.png',
    'Знаток техники': 'IconPerks_gearhead.png',
    'Зов медсестры': 'IconPerks_aNursesCalling.png',
    'Зов на помощь': 'T_UI_iconsPerks_SalvationsCry.png',
    'Игра в открытую': 'IconPerks_open-Handed.png',
    'Изменение плана': 'IconsPerks_ChangeOfPlan.png',
    'Изучение': 'IconPerks_appraisal.png',
    'Им не укрыться': 'IconPerks_nowhereToHide.png',
    'Инстинкт чужого': 'IconPerks_alienInstinct.png',
    'Искажение': 'IconPerks_distortion.png',
    'Истерия': 'IconPerks_hysteria.png',
    'Ищейка': 'IconPerks_bloodhound.png',
    'Как новенький': 'IconPerks_betterThanNew.png',
    'Клоунофобия': 'IconPerks_coulrophobia.png',
    'Коварство': 'IconPerks_insidious.png',
    'Командная работа: быстрая пара': 'IconPerks_teamworkPowerOfTwo.png',
    'Командная работа: общая скрытность': 'IconPerks_teamworkCollectiveStealth.png',
    'Командная работа: полная схема': 'IconsPerks_TeamworkFullCircuit.png',
    'Командная работа: приглушение': 'IconsPerks_TeamworkSoftSpoken.png',
    'Командная работа: скромная победа': 'IconPerks_teamworkToughenUp.png',
    'Командная работа: собраться с силами': 'IconPerks_teamworkThrowDown.png',
    'Корректировка': 'IconPerks_correctiveAction.png',
    'Крепкий орешек': 'IconPerks_deadHard.png',
    'Кровавый договор': 'IconPerks_bloodPact.png',
    'Кровавый смотритель': 'IconPerks_bloodWarden.png',
    'Кровные узы': 'IconPerks_kindred.png',
    'Крушитель': 'IconPerks_saboteur.png',
    'Легковес': 'IconPerks_lightweight.png',
    'Легкоступ': 'IconPerks_light-Footed.png',
    'Лидер': 'IconPerks_leader.png',
    'Ликование': 'IconPerks_Exultation.png',
    'Ловкое приземление': 'IconPerks_balancedLanding.png',
    'Лучшая анатомия': 'IconPerks_superiorAnatomy.png',
    'Лучше вместе': 'IconPerks_betterTogether.png',
    'Любыми средствами': 'IconPerks_anyMeansNecessary.png',
    'Мародерское чутье': 'IconPerks_plunderersInstinct.png',
    'Машинное обучение': 'IconPerks_self-Care.png',
    'Мелкая дичь': 'IconPerks_smallGame.png',
    'Мертвая хватка': 'IconPerks_ironGrasp.png',
    'Место для нас': 'IconsPerks_aPlaceForUs.png',
    'Момент славы': 'IconPerks_MomentOfGlory.png',
    'Мрачные объятья': 'IconPerks_grimEmbrace.png',
    'Мурашки по спине': 'IconPerks_spineChill.png',
    'Мы будем жить вечно': 'IconPerks_wereGonnaLiveForever.png',
    'Мы справимся': 'IconPerks_wellMakeIt.png',
    'Мы тебя видим': 'IconsPerks_WeSeeYou.png',
    'На волю': 'IconPerks_cutLoose.png',
    'На пять шагов впереди': 'IconsPerks_FiveMovesAhead.png',
    'Наблюдение': 'IconPerks_surveillance.png',
    'Надежда': 'IconPerks_hope.png',
    'Напролом': 'IconPerks_headOn.png',
    'Не навреди': 'IconsPerks_DoNoHarm.png',
    'Небесный свидетель': 'T_UI_iconsPerks_CelestialWitness.png',
    'Небрежный мясник': 'IconPerks_sloppyButcher.png',
    'Невыносимое присутствие': 'IconPerks_overwhelmingPresence.png',
    'Незавершенное': 'IconPerks_undone.png',
    'Неистовство': 'T_UI_iconsPerks_Rampage.png',
    'Ненависть': 'IconPerks_rancor.png',
    'Неполадки': 'IconPerks_Haywire.png',
    'Непредвиденное': 'IconPerks_unforeseen.png',
    'Несокрушимый': 'IconPerks_unbreakable.png',
    'Нетерпимость': 'IconPerks_agitation.png',
    'Ниже травы': 'IconPerks_lowProfile.png',
    'Никто не остался позади': 'IconPerks_noOneLeftBehind.png',
    'Нокаут': 'IconPerks_knockOut.png',
    'Нянька': 'IconPerks_babysitter.png',
    'Оберег души': 'IconPerks_soulGuard.png',
    'Обман во благо': 'IconPerks_redHerring.png',
    'Ободрение': 'IconPerks_reassurance.png',
    'Объект одержимости': 'IconPerks_objectOfObsession.png',
    'Оглушительный гром': 'IconPerks_allShakingThunder.png',
    'Одолженное время': 'IconPerks_borrowedTime.png',
    'Оказание помощи': 'T_UI_iconsPerks_LendaHand.png',
    'Опустошение': 'T_UI_iconsPerks_LayWaste.png',
    'Освобождение': 'IconPerks_deliverance.png',
    'Оставленный позади': 'IconPerks_leftBehind.png',
    'Оставьте лучшее напоследок': 'IconPerks_saveTheBestForLast.png',
    'Остаточное проявление': 'IconPerks_residualManifest.png',
    'Отзвук крови': 'IconPerks_bloodEcho.png',
    'Отчаянная борьба': 'IconPerks_powerStruggle.png',
    'Отчаянные меры': 'IconPerks_desperateMeasures.png',
    'Охотник на оленей': 'IconPerks_deerstalker.png',
    'Партнер по сцене': 'IconPerks_scenePartner.png',
    'Перевести часы назад': 'IconsPerks_TurnBackTheClock.png',
    'Перегрузка': 'IconPerks_overcharge.png',
    'Перекрестный допрос': 'T_UI_iconsPerks_CrossExamination.png',
    'Переплетенные навсегда': 'IconPerks_ForeverEntwined.png',
    'Плоды трудов': 'T_UI_iconsPerks_FruitsOfYourLabor.png',
    'Повысить ставки': 'IconPerks_upTheAnte.png',
    'Подрыв': 'IconPerks_eruption.png',
    'Познания в ботанике': 'IconPerks_botanyKnowledge.png',
    'Поиграть со своей жертвой': 'IconPerks_playWithYourFood.png',
    'Полная сосредоточенность': 'IconPerks_hyperfocus.png',
    'Полный газ!': 'T_UI_iconsPerks_WideOpenThrottle.png',
    'Поломка': 'IconPerks_breakdown.png',
    'Помни меня': 'IconPerks_rememberMe.png',
    'Поправка': 'IconPerks_resurgence.png',
    'Порча: благоволение крови': 'IconPerks_hexBloodFavour.png',
    'Порча: в твоей власти': 'T_UI_iconsPerks_HexUnderYourThumb.png',
    'Порча: горькая участь': 'IconPerks_HexWretchedFate.png',
    'Порча: игра для двоих': 'IconPerks_hexTwoCanPlay.png',
    'Порча: игрушка': 'IconPerks_hexPlaything.png',
    'Порча: кара': 'IconPerks_hexRetribution.png',
    'Порча: колыбельная охотницы': 'IconPerks_hexHuntressLullaby.png',
    'Порча: контроль толпы': 'IconPerks_hexCrowdControl.png',
    'Порча: лик мрака': 'IconPerks_hexFaceTheDarkness.png',
    'Порча: не-смерть': 'IconPerks_hexUndying.png',
    'Порча: никому не скрыться от смерти': 'IconPerks_hexNoOneEscapesDeath.png',
    'Порча: охотничий азарт': 'IconPerks_hexThrillOfTheHunt.png',
    'Порча: пентименто': 'IconPerks_hexPentimento.png',
    'Порча: погибель': 'IconPerks_hexRuin.png',
    'Порча: пожирание надежды': 'IconPerks_hexDevourHope.png',
    'Порча: предвестие рока': 'IconPerks_HexOvertureOfDoom.png',
    'Порча: проклятая земля': 'IconPerks_hexHauntedGround.png',
    'Порча: разум улья': 'IconsPerks_HexHiveMind.png',
    'Порча: смертельный испуг': 'T_UI_iconsPerks_ScaredToDeath.png',
    'Порча: только отчаяние': 'IconPerks_NothingButMisery.png',
    'Порча: третья печать': 'IconPerks_hexTheThirdSeal.png',
    'Последний рубеж': 'IconPerks_lastStand.png',
    'Последний этап': 'IconPerks_terminus.png',
    'Поспешное лечение': 'IconPerks_reactiveHealing.png',
    'Потанцуй со мной': 'IconPerks_danceWithMe.png',
    'Потенциальная энергия': 'IconPerks_potentialEnergy.png',
    'Предчувствие': 'IconPerks_premonition.png',
    'Преодоление': 'IconPerks_overcome.png',
    'Преследователь-убийца': 'IconPerks_lethalPursuer.png',
    'Призвание': 'IconPerks_madeForThis.png',
    'Принудительная мера': 'IconPerks_forcedPenance.png',
    'Пристегнись': 'IconPerks_buckleUp.png',
    'Притеснение': 'IconPerks_oppression.png',
    'Проверка на прочность': 'IconPerks_mettleOfMan.png',
    'Проснись': 'IconPerks_wakeUp.png',
    'Противодействие': 'IconPerks_counterforce.png',
    'Прояви себя': 'IconPerks_proveThyself.png',
    'Пугающая тряска': 'IconPerks_thrillingTremors.png',
    'Пугающее присутствие': 'IconPerks_unnervingPresence.png',
    'Равновесие': 'IconPerks_poised.png',
    'Ради людей': 'IconPerks_forThePeople.png',
    'Раз, два, три, четыре!': 'IconPerks_OneTwoThreeFour.png',
    'Разбитые надежды': 'IconPerks_shatteredHope.png',
    'Развитая внимательность': 'IconPerks_awakenedAwareness.png',
    'Разлад': 'IconPerks_discordance.png',
    'Разрушитель разума': 'IconPerks_mindbreaker.png',
    'Раскачка': 'IconPerks_flip-Flop.png',
    'Растворение': 'IconPerks_dissolution.png',
    'Ремонтник': 'IconPerks_troubleshooter.png',
    'Решающий удар': 'IconPerks_decisiveStrike.png',
    'Родительская забота': 'IconPerks_parentalGuidance.png',
    'Розыгрыш': 'IconPerks_bamboozle.png',
    'Рычаг влияния': 'IconPerks_leverage.png',
    'С чистого листа': 'IconPerks_cleanBreak.png',
    'Сам себе доктор': 'IconPerks_self-Care.png',
    'Самосохранение': 'IconPerks_self-Preservation.png',
    'Самоучка': 'IconPerks_autodidact.png',
    'Световая граната': 'IconPerks_flashbang.png',
    'Свирепая гордыня': 'IconPerks_hubris.png',
    'Свободное': 'IconPerks_unbound.png',
    'Связь': 'IconPerks_bond.png',
    'Связь с плетением': 'IconPerks_weaveAttunement.png',
    'Секретный проект': 'IconsPerks_SecretProject.png',
    'Секущий крюк: дар боли': 'IconPerks_scourgeHookGiftOfPain.png',
    'Секущий крюк: пучина ярости': 'IconPerks_scourgeHookFloodsOfRage.png',
    'Секущий крюк: резонанс боли': 'IconPerks_scourgeHookPainResonance.png',
    'Секущий крюк: секрет палача': 'IconPerks_scourgeHookHangmansTrick.png',
    'Секущий крюк: чудовищный храм': 'IconPerks_scourgeHookMonstrousShrine.png',
    'Секущий крюк: щербатый компас': 'IconPerks_scourgeHookJaggedCompass.png',
    'Сеющий страх': 'IconPerks_distressing.png',
    'Сила во мраке': 'IconPerks_strengthInShadows.png',
    'Скользкое мясо': 'IconPerks_slipperyMeat.png',
    'Скопидом': 'IconPerks_hoarder.png',
    'Скрытная погоня': 'IconPerks_furtiveChase.png',
    'Скрытый союз': 'IconPerks_repressedAlliance.png',
    'Слежка и наказание': 'IconPerks_monitorAndAbuse.png',
    'Смертельные узы': 'IconPerks_deathbound.png',
    'Сноровка': 'IconPerks_finesse.png',
    'Собранность': 'IconPerks_innerFocus.png',
    'Совершенное оружие': 'IconPerks_ultimateWeapon.png',
    'Соленое море': 'IconPerks_callOfBrine.png',
    'Солидарность': 'IconPerks_solidarity.png',
    'Состояние потока': 'IconsPerks_FlowState.png',
    'Сострадание': 'IconPerks_empathy.png',
    'Специалист': 'IconPerks_specialist.png',
    'Спокойствие духа': 'IconPerks_calmSpirit.png',
    'Спринтер': 'IconPerks_sprintBurst.png',
    'Стиснув зубы': 'IconPerks_biteTheBullet.png',
    'Стойкий': 'IconPerks_enduring.png',
    'Стридор': 'IconPerks_stridor.png',
    'Строим на века': 'IconPerks_builtToLast.png',
    'Сумеречные шпионы': 'IconPerks_spiesFromTheShadows.png',
    'Счастливая звезда': 'IconPerks_luckyStar.png',
    'Тактика зансин': 'IconPerks_zanshinTactics.png',
    'Танатофобия': 'IconPerks_thanatophobia.png',
    'Темная преданность': 'IconPerks_darkDevotion.png',
    'Темное высокомерие': 'IconPerks_darkArrogance.png',
    'Темное чувство': 'IconPerks_darkSense.png',
    'Территориальный императив': 'IconPerks_territorialImperative.png',
    'Техник': 'IconPerks_technician.png',
    'Тихий шорох': 'IconPerks_bitterMurmur.png',
    'Тлетворное касание': 'IconPerks_septicTouch.png',
    'Товарищество': 'IconPerks_camaraderie.png',
    'Требуются работники': 'IconPerks_HelpWanted.png',
    'Тревога': 'IconPerks_alert.png',
    'Тропа терзаний': 'IconPerks_trailOfTorment.png',
    'Туз в рукаве': 'IconPerks_aceInTheHole.png',
    'Убежденность': 'IconPerks_conviction.png',
    'Угасающий свет': 'IconPerks_dyingLight.png',
    'Ударный забег': 'IconPerks_smashHit.png',
    'Уловка': 'IconPerks_deception.png',
    'Умелец': 'IconPerks_tinkerer.png',
    'Умудренный туманом': 'IconPerks_fogwise.png',
    'Уникальная возможность': 'IconPerks_windowsOfOpportunity.png',
    'Уроки улиц': 'IconPerks_streetwise.png',
    'Усердие': 'IconPerks_overzealous.png',
    'Устойчивость': 'IconPerks_resilience.png',
    'Утилизатор': 'IconPerks_scavenger.png',
    'Уход за больным': 'IconPerks_aftercare.png',
    'Фанатение': 'IconPerks_starstruck.png',
    'Фантомный страх': 'IconPerks_PhantomFear.png',
    'Фиксация': 'IconPerks_fixated.png',
    'Форсаж': 'IconPerks_breakout.png',
    'Фугасная мина': 'IconPerks_blastMine.png',
    'Химическая ловушка': 'IconPerks_chemicalTrap.png',
    'Хищник': 'IconPerks_predator.png',
    'Хищный зверь': 'IconPerks_beastOfPrey.png',
    'Чары: пауки-прядильщики': 'IconPerks_invocationWeavingSpiders.png',
    'Чары: предательские вороны': 'IconPerks_invocationTreacherousCrows.png',
    'Через край': 'IconPerks_boilOver.png',
    'Чертик из табакерки': 'IconPerks_popGoesTheWeasel.png',
    'Чуткий слух': 'IconPerks_imAllEars.png',
    'Шепоты': 'IconPerks_whispers.png',
    'Эй, я здесь!': 'IconPerks_comeAndGetMe.png',
    'Эмпатическая связь': 'IconPerks_empathicConnection.png',
    'Этому не бывать': 'IconPerks_thisIsNotHappening.png',
    'Явление мрака': 'IconPerks_darknessRevealed.png',
    'Яркое пламя': 'IconPerks_fireUp.png',
    'Ярость духа': 'IconPerks_spiritFury.png',
    'Ясновидение': 'IconPerks_clairvoyance.png',
}
