# -*- coding: utf-8 -*-
"""Карта «русское имя аддона (как в dbd_data.py) -> английское имя на wiki.gg».

Нужна ТОЛЬКО для генерации карты иконок ADDON_ICONS (tools/resolve_addon_icons.py):
имена файлов иконок на deadbydaylight.wiki.gg образованы от английских названий,
а в игре и в базе у нас русские. В рантайме приложения не используется.

Сверено с Module:Datatable/Loadout wiki.gg (патч 10.1.2a). Аддоны, которых нет в
живом списке wiki.gg (выведены из игры), в карту не попали — иконки у них нет.
"""

ADDON_RU_EN = {
    "Охотник": {
        "Кровавая пружина": "Bloody Coil", "Радужный камень": "Iridescent Stone",
        "Маслянистая пружина": "Oily Coil", "Натяжная пружина": "Tension Spring",
        "Охотничий мешок": "Trapper Sack", "Точильный камень": "Honing Stone",
        "Дополнительная пружина": "Secondary Coil", "Крепежные инструменты": "Fastening Tools",
        "Охотничья сумка": "Trapper Bag", "Ржавые челюсти": "Rusted Jaws",
        "Смоляная бутылка": "Tar Bottle", "Зазубренные челюсти": "Serrated Jaws",
        "Комплект из 4-х спиральных пружин": "4-Coil Spring Kit", "Кофейная гуща": "Coffee Grounds",
        "Кусок воска": "Wax Brick", "Удлиненная челюсть": "Lengthened Jaws",
        "Медвежий жир": "Bear Oil", "Мягкие челюсти": "Padded Jaws",
        "Охотничьи перчатки": "Trapper Gloves", "Самодельный бандаж": "Makeshift Wrap",
    },
    "Призрак": {
        "Всевидящий - дух": '"All Seeing" - Spirit', "Всевидящий - кровь": '"All Seeing" - Blood',
        "Стремительная охота - кровь": '"Swift Hunt" - Blood',
        "Стремительная охота - белая краска": '"Swift Hunt" - White',
        "Стремительная охота - грязь": '"Swift Hunt" - Mud',
        "Танец теней - кровь": '"Shadow Dance" - Blood',
        "Танец теней - белая краска": '"Shadow Dance" - White',
        "Ураган - кровь": '"Windstorm" - Blood', "Ураган - белая краска": '"Windstorm" - White',
        "Ураган - грязь": '"Windstorm" - Mud', "Скачок - белая краска": '"Blink" - White',
        "Скачок - грязь": '"Blink" - Mud', "Слепой воин - белая краска": '"Blind Warrior" - White',
        "Слепой воин - грязь": '"Blind Warrior" - Mud', "Костяной язычок колокола": "Bone Clapper",
        "Гоуст Фейс - сажа": '"The Ghost" - Soot', "Зверь - сажа": '"The Beast" - Soot',
        "Змей - сажа": '"The Serpent" - Soot', "Ищейка - сажа": '"The Hound" - Soot',
    },
    "Деревенщина": {
        "Шипастые сапоги": "Spiked Boots", "Радужные гравюры": "Iridescent Engravings",
        "Кукурузный самогон": "The Thompsons' Mix", "Низкой отдачей": "Low Kickback Chains",
        "Самонастраивающийся карбюратор": "Tuned Carburettor", "Грязные цепи": "Begrimed Chains (Chainsaw)",
        "Ботинки с железными мысками": "Steel Toe Boots",
    },
    "Медсестра": {
        "Порванная закладка": "Torn Bookmark", "Спичечный коробок": "Matchbox",
        "Последний вздох «Плохиша»": "\"Bad Man's\" Last Breath",
        "Последний вздох Кэмпбелла": "Campbell's Last Breath",
        "Последний вздох Дженнер": "Jenner's Last Breath",
        "Последний вздох Каваны": "Kavanagh's Last Breath",
        "Судорожный вздох": "Spasmodic Breath",
        "Карманные часы": "Pocket Watch (Spencer's Last Breath)",
        "Деревянная лошадка": "Wooden Horse",
    },
    "Тень": {
        "Надгробие Джудит": "Judith's Tombstone", "Поцарапанное зеркало": "Scratched Mirror",
        "Дамское зеркало": "Vanity Mirror", "Кусок надгробия": "Tombstone Piece",
        "Прядь волос": "Lock of Hair", "Светоотражающий осколок": "Reflective Fragment",
        "Бант для волос": "Hair Bow", "В память о Дж. Майерс": "J. Myers Memorial",
        "Дневник Джудит": "Judith's Journal", "Коробка с бижутерией": "Jewellery Box",
        "Осколок зеркала": "Mirror Shard", "Ароматный клок волос": "Fragrant Tuft of Hair",
        "Бижутерия": "Jewellery", "Мертвый кролик": "Dead Rabbit", "Осколок стекла": "Glass Fragment",
        "Расческа для волос": "Hair Brush", "Безвкусные серьги": "Tacky Earrings",
        "Записка от парня": "Boyfriend's Memo", "Мемориальный цветок": "Memorial Flower",
        "Светлый волос": "Blond Hair",
    },
    "Ведьма": {
        "Вымокший ботинок": "Waterlogged Shoe", "Зеленая тряпка": "Mint Rag",
        "Бабушкино сердце": "Grandma's Heart", "Обезображенное ухо": "Disfigured Ear",
        "Ржавые кандалы": "Rusty Shackles", "Рука со шрамом": "Scarred Hand",
        "Ивовый венок": "Willow Wreath", "Кровавая грязь": "Bloodied Mud",
        "Ожерелье из болотной орхидеи": "Swamp Orchid Necklet",
        "Разбитое яйцо черепахи": "Cracked Turtle Egg", "Сушеная цикада": "Dried Cicada",
        "Кипарисовое ожерелье": "Cypress Necklet",
    },
    "Доктор": {
        "Радужный король": "Iridescent King", "Радужный ферзь": "Iridescent Queen",
        "«Дисциплина» — заметки Картера": '"Discipline" - Carter\'s Notes',
        "«Порядок» — заметки Картера": '"Order" - Carter\'s Notes',
        "«Спокойствие» — заметки Картера": '"Calm" - Carter\'s Notes',
        "«Усмирение» — заметки Картера": '"Restraint" - Carter\'s Notes',
    },
    "Охотница": {
        "Радужный топор": "Iridescent Head", "Солдатские портянки": "Soldier's Puttee",
        "Деревянная лиса": "Wooden Fox", "Испачканный топор": "Begrimed Head",
        "Разгрузочный пояс": "Infantry Belt", "Светящаяся смесь": "Glowing Concoction",
        "Бабушкин платок": "Flower Babushka", "Перчатки из оленевой кожи": "Deerskin Gloves",
        "Ржавый топор": "Rusty Head", "Розовый корень": "Rose Root",
        "Ядовитая смесь": "Venomous Concoction", "Венок из манника": "Manna Grass Braid",
        "Дубовое топорище": "Oak Haft", "Кожаная петля": "Leather Loop", "Сияющая брошь": "Shiny Pin",
        "Утяжеленный топор": "Weighted Head", "Грубый оселок": "Coarse Stone",
    },
    "Каннибал": {
        "Переливчатая плоть": "Iridescent Flesh",
        "Руководство по настройке карбюратора": "Carburettor Tuning Guide",
        "Облегченное шасси": "Light Chassis", "Ограничитель для заточки цепи": "Depth Gauge Rake",
        "Ржавая цепь": "Rusted Chains", "Чили-победитель состязания": "Award-winning Chilli",
        "Грязные цепи": "Begrimed Chains (Bubba's Chainsaw)", "Метки зверя": "The Beast's Marks",
        "Производственная смазка": "Shop Lubricant", "Смазка": "The Grease",
        "Ужасная цепь": "Grisly Chains", "Длинное реле для бензопилы": "Long Guide Bar",
        "Метки ножом": "Knife Scratches", "Самодельный глушитель": "Homemade Muffler",
        "Сжимной насос": "Primer Bulb", "Чили": "Chilli", "Напильник для бензопилы": "Chainsaw File",
    },
    "Кошмар": {
        "Красная кисть": "Red Paint Brush", "Черная коробка": "Black Box",
        "Групповое фото": "Class Photo", "Кубик с буквой «Z»": '"Z" Block',
        "Пузырек для лекарства": "Pill Bottle", "Цепь от качелей": "Swing Chains",
        "Голубое платье": "Blue Dress", "Кубик с единорогом": "Unicorn Block",
        "Растворитель для краски": "Paint Thinner", "Скакалка": "Jump Rope (Dream Demon)",
        "Шедевр Нэнси": "Nancy's Masterpiece", "Зеленое платье": "Green Dress",
        "Крепкая веревка": "Outdoor Rope", "Кубик с кошкой": "Cat Block",
        "Прототип перчатки с лезвиями": "Prototype Claws", "Эскиз Нэнси": "Nancy's Sketch",
        "Детский рисунок": "Kid's Drawing", "Кубик с овцами": "Sheep Block",
        "Садовые грабли": "Garden Rake", "Шерстяная рубашка": "Wool Shirt",
    },
    "Свинья": {
        "Видеокассета": "Video Tape", "Письмо Аманды": "Amanda's Letter",
        "Модифицированный таймер": "Tampered Timer", "Набросок Пилы": "Jigsaw's Sketch",
        "Секрет Аманды": "Amanda's Secret", "Ящик с шестеренками": "Crate of Gears",
        "Мешок с шестеренками": "Bag of Gears", "Набор правил №2": "Rules Set No.2",
        "Подробный план Пилы": "Jigsaw's Annotated Plan", "Ржавые клыки": "Rusty Attachments",
        "Токсин медленного действия": "Slow-Release Toxin", "Завещание": "Last Will",
        "Колючая проволока": "Razor Wires", "Лезвия": "Utility Blades", "Лицевая маска": "Face Mask",
    },
    "Клоун": {
        "Мизинец рыжей девушки": "Redhead's Pinkie Finger",
        "Татуированный средний палец": "Tattoo's Middle Finger", "15-процентный эфир": "Ether 15 Vol%",
        "Бутылка дешевого джина": "Cheap Gin Bottle", "Коробка из-под сигар": "Cigar Box",
        "Набор яркого грима": "Garish Make-Up Kit", "Бутылка хлороформа": "Bottle of Chloroform",
        "Вонючие стельки": "Smelly Inner Soles", "Мензурка с отбеливателем": "Flask of Bleach",
        "Нашатырный спирт": "Spirit of Hartshorn", "Пробирка с серной кислотой": "Sulphuric Acid Vial",
        "Канистра керосина": "Kerosene Can", "Липкая бутылка из-под газировки": "Sticky Soda Bottle",
        "Перо скворца": "Starling Feather", "Сосуд с растворителем": "Solvent Jug",
        "Толстая пробка": "Thick Cork Stopper", "Бутылка для вечеринки": "Party Bottle",
        "Клоунские перчатки без пальцев": "Fingerless Parade Gloves", "Перо малиновки": "Robin Feather",
        "Порнуха на кассете": "VHS Porn",
    },
    "Дух": {
        "Кольцо от мамы": "Mother-Daughter Ring", "Чашка кинцуги": "Kintsugi Teacup",
        "Амулет Якуёкэ": "Yakuyoke Amulet", "Высушенный цветок вишни": "Dried Cherry Blossom",
        "Сая вакидзаси": "Wakizashi Saya", "Фурин": "Furin", "Очки матери": "Mother's Glasses",
        "Ржавая флейта": "Rusty Flute", "Сэнко ханаби": "Senko Hanabi", "Утива": "Uchiwa",
        "Цуба катаны": "Katana Tsuba", "Белый бант": "White Hair Ribbon",
        "Грязная бейсболка": "Muddy Sports Day Cap", "Можжевеловый бонсай": "Juniper Bonsai",
        "Сломанные часы Рин": "Rin's Broken Watch", "Талисман каиун": "Kaiun Talisman",
        "Амулет сиавасэ": "Shiawase Amulet", "Дзори": "Zōri", "Журавль оригами": "Origami Crane",
        "Подаренная бамбуковая расческа": "Gifted Bamboo Comb",
    },
    "Легион": {
        "Радужная кнопка": "Iridescent Button", "Дымящаяся кассета": "Fuming Mix Tape",
        "Грязный нож": "Filthy Blade", "Дружба на века": "BFFs",
        "Исследование колотых ран": "Stab Wounds Study", "Кассета Фрэнка": "Frank's Mix Tape",
        "Значок Легиона": "The Legion Pin", "Кассета Джо": "Joey's Mix Tape",
        "Кассета Сузи": "Susie's Mix Tape", "Стильные темные очки": "Stylish Sunglasses",
        "Украденный альбом": "Stolen Sketch Book", "Безликий значок-смайлик": "Defaced Smiley Pin",
        "Кассета Джули": "Julie's Mix Tape", "Линейка с гравировкой": "Etched Ruler",
        "Рисунок на стене": "Mural Sketch", "Таблетки от сна": "Never-Sleep Pills",
        "Браслет дружбы": "Friendship Bracelet", "Значок-смайлик": "Smiley Face Pin",
        "Поцарапанная линейка": "Scratched Ruler", "Список непослушных": "Mischief List",
    },
    "Чума": {
        "Радужная печать": "Iridescent Seal", "Черный фимиам": "Black Incense",
        "Амулет ревнителя": "Devotee's Amulet", "Зловещее рвотное": "Vile Emetic",
        "Отрезанный палец": "Severed Toe", "Скрижаль поклонения": "Worship Tablet",
        "Амулет экзорцизма": "Exorcism Amulet", "Благовонная мазь": "Incensed Ointment",
        "Зараженное рвотное": "Infected Emetic", "Масло для растираний": "Rubbing Oil",
        "Яблоко праха": "Ashen Apple", "Амулет предотвращения": "Prophylactic Amulet",
        "Гематитовая пломба": "Haematite Seal", "Освященное яблоко": "Blessed Apple",
        "Рвотное": "Emetic Potion", "Сильная микстура": "Potent Tincture",
        "Пломба из песчаника": "Limestone Seal",
    },
    "Гоуст Фейс": {
        "«Гоуст Фейс пойман на камеру»": '"Ghost Face Caught on Tape"',
        "Наружная камера наблюдения": "Outdoor Security Camera", "Водительские права": "Driver's License",
        "Монокуляр ночного видения": "Night Vision Monocular", "Набедренные ножны": "Drop-Leg Knife Sheath",
        "Распорядок дня жертвы": "Victim's Detailed Routine", "Зажим для ремня": "Knife Belt Clip",
        "Кожаные ножны": "Leather Knife Sheath", "Кошелек Олсена": "Olsen's Wallet",
        "Погрызенная ручка": "Chewed Pen", "Стойкий парфюм": "Lasting Perfume",
        "Адресная книга Олсена": "Olsen's Address Book", "Дневник Олсена": "Olsen's Journal",
        "Карта с метками": "Marked Map", "Ремешки": "Cinch Straps", "Телеобъектив": "Telephoto Lens",
        "«Филадельфия»": '"Philly"', "Вырезки из газет": "Headline Cut-Outs",
        "Дешевый одеколон": "Cheap Cologne", "Спичечный коробок из «Судака»": "Walleye's Matchbook",
    },
    "Демогоргон": {
        "Красный мох": "Red Moss", "Чешуйчатый лишайник": "Leprose Lichen",
        "Киноварный паутинник": "Vermilion Webcap", "Свисток спасателя": "Lifeguard Whistle",
        "Смола с изнанки": "Upside Down Resin", "Странное яйцо": "Unknown Egg",
        "Банка одиннадцатой": "Eleven's Soda", "Легкое оленя": "Deer Lung",
        "Медная зажигалка": "Brass Case Lighter", "Пурпурная влажноголовка": "Violet Waxcap",
        "Шипастые лозы": "Thorny Vines", "Кишки мяуса": "Mews' Guts",
        "Клейкая паутина": "Viscous Webbing", "Липкая слизь": "Sticky Lining",
        "Очки Барб": "Barb's Glasses", "Протухшая требуха": "Rotten Green Tripe",
    },
    "Они": {
        "Окровавленная перчатка Рендзиро": "Renjiro's Bloody Glove",
        "Переливчатый семейный герб": "Iridescent Family Crest", "Костыль Акито": "Akito's Crutch",
        "Львиный клык": "Lion Fang", "Мокрое от слез тэнугуи": "Tear-Soaked Tenugui",
        "Разбитый корпус": "Splintered Hull", "Деревянная маска Они": "Wooden Oni Mask",
        "Расколотый вакидзаси": "Shattered Wakizashi", "Сасимоно семьи Ямаока": "Yamaoka Sashimono",
        "Скальп с пучком волос": "Scalped Topknot", "Талисман Канай Андзэн": "Kanai-Anzen Talisman",
        "Блестящий маэдатэ": "Polished Maedate", "Детский деревянный меч": "Child's Wooden Sword",
        "Лев, нарисованный тушью": "Ink Lion", "Окровавленная повязка": "Bloody Sash",
    },
    "Стрелок": {
        "Радужная монета": "Iridescent Coin", "Хелширское клеймо": "Hellshire Iron",
        "Виски «Голд Крик»": "Gold Creek Whiskey", "Колючая проволока": "Barbed Wire",
        "Сигара Бейшора": "Bayshore's Cigar", "Тюремная цепь": "Prison Chain",
        "Жестяная масленка": "Tin Oil Can", "Золотой зуб Бейшора": "Bayshore's Gold Tooth",
        "Ключи начальника тюрьмы": "Warden's Keys", "Колючки гледичии": "Honey Locust Thorn",
        "Плакат «В розыске»": "Wanted Poster", "Жевательный табак": "Chewing Tobacco",
        "Значок шерифа": "Marshal's Badge", "Зубодробилка": "Jaw Smasher",
    },
    "Палач": {
        "Обсидиановый кубок": "Obsidian Goblet", "Радужная печать Метатрона": "Iridescent Seal of Metatron",
        "Алое яйцо": "Scarlet Egg", "Книга «Багровая церемония»": "Crimson Ceremony Book",
        "Книга «Потерянные воспоминания»": "Lost Memories Book", "Яйцо цвета ржавчины": "Rust-Coloured Egg",
        "Рисунок «Горящий человек»": "Burning Man Painting", "Стопа манекена": "Mannequin Foot",
        "Табличка угнетателя": "Tablet of the Oppressor",
        "Туманный день, останки правосудия": "Misty Day, Remains of Judgement",
        "Фотография секты Валтиэля": "Valtiel Sect Photograph", "Восковая кукла": "Wax Doll",
        "Забытая видеокассета": "Forgotten Videotape", "Леопардовая ткань": "Leopard-Print Fabric",
        "Музыкальная шкатулка с золушкой": "Cinderella Music Box",
    },
    "Мор": {
        "Переливчатая бирка Мора": "Iridescent Blight Tag", "Состав №33": "Compound Thirty-Three",
        "Вещество души": "Soul Chemical", "Дневник Виго": "Vigo's Journal",
        "Камень призыва": "Summoning Stone", "Кольцо алхимика": "Alchemist's Ring",
        "Изуродованная ворона": "Blighted Crow", "Розовый тоник": "Rose Tonic",
        "Состав №21": "Compound Twenty-One", "Теневые соли": "Umbra Salts",
        "Флакон с адреналином": "Adrenaline Vial", "Желчь чумы": "Plague Bile",
        "Изуродованная крыса": "Blighted Rat", "Порванные записи": "Shredded Notes",
        "Порошок гнойника": "Pustula Dust", "Шип язвенника": "Canker Thorn",
        "Монокль со сколами": "Chipped Monocle",
    },
    "Близнецы": {
        "Переливчатый кулон": "Iridescent Pendant", "Тряпичный кляп": "Silencing Cloth",
        "Волчок": "Spinning Top", "Капля парфюма": "Drop of Perfume", "Лесное рагу": "Forest Stew",
        "Солдатик Виктора": "Victor's Soldier", "Канализационная слякоть": "Sewer Sludge",
        "Ржавая иголка": "Rusted Needle", "Увесистая погремушка": "Weighty Rattle",
        "Черствый хлебец": "Stale Biscuit", "Шарф Мадлен": "Madeleine's Scarf",
        "Кошачий глаз": "Cat's Eye", "Молочные зубы": "Baby Teeth", "Перчатка Мадлен": "Madeleine's Glove",
    },
    "Трюкач": {
        "Переливающийся снимок": "Iridescent Photocard",
        "Сборник «Предсмертные муки»": "Death Throes Compilation",
        "Альбом «Край возрождения»": "Edge of Revival Album", "Бриллиантовые запонки": "Diamond Cufflinks",
        "Сингл «Сквозь тебя»": "Cut Thru U Single", "Трюковые ножи": "Trick Blades",
        "Мелодичное убийство": "Melodious Murder", "Напульсник из «Потрошителя»": "Ripper Brace",
        "Сингл «Вижу цель»": "On Target Single", "Часы-реквизит": "Waiting For You Watch",
        "Шипучка без прикрас": "Fizz-Spin Soda", "Автограф Чиуна": "Ji-Woon's Autograph",
    },
    "Немезис": {
        "Переливчатый значок Umbrella": "Iridescent Umbrella Badge",
        "Расколотый значок S.T.A.R.S.": "Shattered S.T.A.R.S. Badge",
        "Израсходованная чернильная лента": "Depleted Ink Ribbon", "Паразит NE-A (NE-альфа)": "NE-a Parasite",
        "Сломанная монета восстановления": "Broken Recovery Coin", "Сэндвич Джилл": "Jill's Sandwich",
        "Лианы образца 43": "Plant 43 Vines", "Образец Т-вируса": "T-Virus Sample",
        "Останки Тирана": "Tyrant Gore", "Шприц с серотонином": "Serotonin Injector",
        "Язык лизуна": "Licker Tongue", "Браслет администратора": "Admin Wristband",
        "Глаз Михаила": "Mikhail's Eye", "Кровь Марвина": "Marvin's Blood",
        "Сердце зомби": "Zombie Heart", "Шприц с адреналином": "Adrenaline Injector",
        "Гостевой браслет": "Visitor Wristband", "Кишки Брайана": "Brian's Intestine",
        "Поврежденный шприц": "Damaged Syringe", "Полевой справочник S.T.A.R.S.": "S.T.A.R.S. Field Combat Manual",
    },
    "Сенобит": {
        "Клык инженера": "Engineer's Fang",
        "Переливчатая Конфигурация Плача": "Iridescent Lament Configuration",
        "Зуб щелкунчика": "Chatterer's Tooth", "Исходная боль": "Original Pain",
        "Пронзающая проволока": "Impaling Wire", "Сальная черная линза": "Greasy Black Lens",
        "Колонна терзаний": "Torture Pillar", "Кровь Ларри": "Larry's Blood",
        "Останки Ларри": "Larry's Remains", "Ошметок Фрэнка": "Slice of Frank",
        "Сердце Фрэнка": "Frank's Heart", "Мерцающий телевизор": "Flickering Television",
        "Пронзенная крыса": "Skewered Rat", "Сгнившая еда": "Spoiled Meal",
        "Сжиженные останки": "Liquified Gore", "Шевелящиеся личинки": "Wriggling Maggots",
        "Бодрые сверчки": "Lively Crickets",
    },
    "Художница": {
        "Автопортрет": "Automatic Drawing", "Масляные краски": "Oil Paints",
        "Бархатная ткань": "Velvet Fabric", "Вороний натюрморт": "Still Life Crow",
        "Отрубленные руки": "Severed Hands", "Агония без названия": "Untitled Agony",
        "Колючее гнездо": "Thorny Nest", "О горечь и любовь моя": "O Grief, O Lover",
        "Серебряный колокольчик": "Silver Bell", "Темнейшая тушь": "Darkest Ink",
        "Угольная палочка": "Charcoal Stick", "Ботиночки Матиаса": "Matias' Baby Shoes",
        "Отрезанный язык": "Severed Tongue", "Сад гнили": "Garden of Rot",
        "Переливчатое перо": "Iridescent Feather", "Чернильное яйцо": "Ink Egg",
        "Гниющие останки": "Festering Carrion", "Густое варево": "Thick Tar",
        "Красочный некролог": "Vibrant Obituary", "Кукуруза чокло": "Choclo Corn",
    },
    "Онрё": {
        "Пульт от видика": "Remote Control", "Радужная кассета": "Iridescent Videotape",
        "Видеомагнитофон": "VCR", "Искаженное фото": "Distorted Photo",
        "Монтажный пульт": "Tape Editing Deck", "Телефон": "Telephone", "Вода из колодца": "Well Water",
        "Окровавленные ногти": "Bloody Fingernails", "Расческа матери": "Mother's Comb",
        "Рисунок кольца": "Ring Drawing", "Хлипкая игрушка": "Rickety Pinwheel",
        "Колодезный камень": "Well Stone", "Лохмы": "Clump of Hair", "Просоленная ткань": "Sea-Soaked Cloth",
    },
    "Грязь": {
        "Жертвенный нож": "Sacrificial Knife", "Радужная деревянная доска": "Iridescent Wooden Plank",
        "Диктофон": "Field Recorder", "Ключ от судна": "Boat Key", "Пахотный инструмент": "Tilling Blade",
        "Петличный микрофон": "Lavalier Microphone", "Камушек беспокойства": "Worry Stone",
        "Оттомарские записи": "Ottomarian Writing", "Разодранная подушка": "Destroyed Pillow",
        "Сломанная кукла": "Broken Doll", "Солдатский шлем": "War Helmet",
        "Календарь Хэдди": "Haddie's Calendar", "Освежитель воздуха": "Air Freshener",
        "Сожженные письма": "Burnt Letters", "Упавшая дранка": "Fallen Shingle",
    },
    "Кукловод": {
        "Радужная склянка «Уробороса»": "Iridescent Uroboros Vial", "Фото из лаборатории": "Lab Photo",
        "Вертолетный руль": "Helicopter Stick", "Вирус «Уроборос»": "Uroboros Virus",
        "Темные очки": "Dark Sunglasses", "Красная трава": "Red Herb",
        "Медальон с дамой": "Maiden Medallion", "Переносной сейф": "Portable Safe",
        "Устройство видеосвязи": "Video Conference Device", "Зеленая трава": "Green Herb",
        "Златка": "Jewel Beetle", "Медальон со львом": "Lion Medallion",
        "Отвалившаяся ручка": "Loose Crank", "Рупор": "Bullhorn", "Яйцо (золотое)": "Egg (Gold)",
        "Кожаные перчатки": "Leather Gloves", "Кубок (золотой)": "Chalice (Gold)",
        "Медальон с единорогом": "Unicorn Medallion", "Ошметок «Уробороса»": "Uroboros Tendril",
        "Полицейская рация": "R.P.D. Shoulder Walkie",
    },
    "Рыцарь": {
        "Радужное знамя отряда": "Iridescent Company Banner", "Рыцарский договор": "Knight's Contract",
        "Исцеляющая припарка": "Healing Poultice", "Колокольчики тюремщика": "Jailer's Chimes",
        "Кремень и сталь": "Flint and Steel", "Кузнечный молот": "Blacksmith's Hammer",
        "Заостренная опора": "Sharpened Mount", "Караульный факел": "Town Watch's Torch",
        "Кузнечные щипцы": "Ironworker's Tongs", "Мрачная железная маска": "Grim Iron Mask",
        "Сломанная рукоять": "Broken Hilt", "Вяленая конина": "Dried Horsemeat",
        "Лезвие боевого топора": "Battle Axe Head", "Призыв к оружию": "Call to Arms",
        "Протравленный клинок": "Treated Blade", "Стальные кандалы": "Cold Steel Manacles",
    },
    "Торговка черепами": {
        "Радужная неопубликованная рукопись": "Iridescent Unpublished Manuscript",
        "Разряженные аккумуляторы": "Expired Batteries",
        "Расширенный прогноз перемещений": "Advanced Movement Prediction",
        "Случайные импульсы": "Randomised Strobes", "Считывание геоданных": "Geographical Readout",
        "Экспериментальный винт": "Prototype Rotor", "Анализатор уязвимостей": "Vital Targeting Processor",
        "Генератор красного шума": "Brown Noise Generator", "Инфракрасный модуль": "Infrared Upgrade",
        "Ослабленные винты": "Loose Screw", "Толченое стекло": "Powdered Glass",
        "Адаптивное освещение": "Adaptive Lighting", "Оглушающие динамики": "Shotgun Speakers",
        "Режим энергосбережения": "Low-Power Mode", "Сверхнапряжение": "Supercharge",
        "Стереорадиомикрофон": "Stereo Remote Mic", "Ади Валенте №1": "Adi Valente Issue 1",
        "Высокоамперный усилитель": "High-Current Upgrade", "Мощный прожектор": "High-Power Floodlight",
        "Ультразвуковой динамик": "Ultrasonic Speaker",
    },
    "Сингулярность": {
        "Радужный осколок кристалла": "Iridescent Crystal Shard",
        "Форма заявки с отказом": "Denied Requisition Form",
        "Волокна неизвестных растений": "Foreign Plant Fibres",
        "Инструмент диагностики (строительство)": "Diagnostic Tool (Construction)",
        "Семейная фотография Сома": "Soma Family Photo", "Список экипажа": "Crew Manifest",
        "Гель с наномашинами": "Nanomachine Gel", "Генератор голограмм": "Hologram Generator",
        "Провода под напряжением": "Live Wires", "Пустой кислородный баллон": "Spent Oxygen Tank",
        "Спрей гипервнимательности": "Hyperawareness Spray",
        "Детская бейсбольная перчатка": "Kid's Ball Glove", "Кремированные останки": "Cremated Remains",
        "Криогель": "Cryo Gel", "Рука андроида": "Android Arm",
    },
    "Ксеноморф": {
        "Импровизированный электрохлыст": "Improvised Cattle Prod", "Кислотная кровь": "Acidic Blood",
        "Болт самоуничтожения": "Self-Destruct Bolt", "Гарпун": "Harpoon Gun",
        "Кошачья переноска": "Cat Carrier", "Семиотическая клавиатура": "Semiotic Keyboard",
        "Аварийный шлем": "Emergency Helmet", "Повязка Паркера": "Parker's Headband",
        "Растекшаяся шкурка": "Moulted Skin", "Универсальный топор": "Multipurpose Hatchet",
        "Шлем Кейна": "Kane's Helmet", "Внутренности Эша": "Ash's Innards",
        "Гарнитура экипажа": "Crew Headset", "Звездная карта Ламберт": "Lambert's Star Map",
        "Кепка Бретта": "Brett's Cap",
    },
    "Хороший парень": {
        "Жесткая шляпа": "Hard Hat", "Радужный амулет": "Iridescent Amulet", "Кучка гвоздей": "Pile of Nails",
        "Опасная бритва": "Straight Razor", "Осколки зеркала": "Mirror Shards (Playtime's Over)",
        "Пластиковый мешок": "Plastic Bag", "Беговая обувь": "Running Shoes", "Крысиный яд": "Rat Poison",
        "Линейка": "Yardstick", "Переносной телик": "Portable TV", "Шелковая подушка": "Silk Pillow",
        "Перфоратор": "Power Drill", "Разделочный электронож": "Electric Carving Knife",
        "Свечка и лак для волос": "Hair Spray & Candle", "Скакалка": "Jump Rope (Playtime's Over)",
        "Шуруповерт": "Automatic Screwdriver", "Коробка «Хороший парень»": "Good Guy Box",
        "Крошечный скальпель": "Tiny Scalpel", "Кукольные глаза": "Doll Eyes", "Мерцающий свет": "Strobing Light",
    },
    "Неведомое": {
        "В ловушке мрака": "Captured by the Dark", "Радужный доклад УСС": "Iridescent OSS Report",
        "Иссеченный рюкзак": "Slashed Backpack", "Проткнутый глаз": "Punctured Eyeball",
        "Картридж с жуткой игрой": "Obscure Game Cartridge", "Исчезающая шкатулка": "Vanishing Box",
        "Самодельная маска": "Homemade Mask", "Часы гипнотизера": "Hypnotist's Watch",
        "Пустой пакет из-под молока": "Discarded Milk Carton", "Склянка с сывороткой": "Serum Vial",
        "Карта жертвы": "Victim's Map", "Афиша второсортного фильма": "B-Movie Poster",
        "Блокнот с предложениями": "Notebook of Theories", "Последние звуки": "Last Known Recording",
        "Размытое фото": "Blurry Photo", "Кроличья лапка": "Rabbit's Foot", "Передовица": "Front-Page Article",
        "Слепок следа": "Footprint Cast", "Устройство неизвестного назначения": "Device of Undisclosed Origin",
        "Неаккуратный набросок": "Sketch Attempt",
    },
    "Лич": {
        "Вострый меч": "Vorpal Sword", "Радужная книга гнусной тьмы": "Iridescent Book of Vile Darkness",
        "Бездонная сумка": "Bag of Holding", "Глазастая мантия": "Robe of Eyes",
        "Кинжал из зуба дракона": "Dragontooth Dagger", "Плащ невидимости": "Cloak of Invisibility",
        "Жемчужина силы": "Pearl of Power", "Посох увядания": "Staff of Withering",
        "Сапоги скорости": "Boots of Speed", "Украшенный рог": "Ornate Horn",
        "Эльфийский плащ": "Cloak of Elvenkind", "Зелье скорости": "Potion of Speed",
        "Кольцо телекинеза": "Ring of Telekinesis", "Кольцо хранения заклинаний": "Ring of Spell Storing",
        "Стеклянный глаз": "Glass Eye", "Фонарь разоблачения": "Lantern of Revealing",
    },
    "Тёмный властелин": {
        "Радужное кольцо Влада": "Iridescent Ring of Vlad", "Щит Алукарда": "Alucard's Shield",
        "Волосы медузы": "Medusa's Hair", "Клык Варга": "Warg's Fang", "Куб Зои": "Cube of Zoe",
        "Ляпис-Лазурь": "Lapis Lazuli", "Карманные часы": "Pocket Watch (Vampiric Shift)",
        "Кукла-убийца": "Killer Doll", "Перо сильфы": "Sylph Feather", "Сила эха": "Force of Echo",
        "Солнцезащитные очки": "Sunglasses", "Волшебный билет": "Magical Ticket",
        "Крылатая обувь": "Winged Boots", "Медальон белого волка": "White Wolf Medallion",
        "Ожерелье с лунным камнем": "Moonstone Necklace", "Чаша с кровью": "Blood-Filled Goblet",
        "Коготь цербера": "Cerberus Talon", "Рубиновый венец": "Ruby Circlet",
        "Снаряжение «Часовая башня»": "Clock Tower Gear", "Шляпа путника": "Traveller's Hat",
    },
    "Егерь": {
        "Порванная книга": "Torn Novel", "Радужный штурвал": "Iridescent Wheel Handle",
        "Банка пороха": "Gunpowder Tin", "Кожаная сбруя": "Leather Harness",
        "Носовая фигура": "Ship Figurehead", "Свайка": "Marlinspike", "Бурдюк": "Waterskin",
        "Жирное мясо": "Fatty Meat", "Незаконченная карта": "Unfinished Map",
        "Ошейник с шипами": "Spiked Collar", "Тренировочный колокольчик": "Training Bell",
        "Веревка с узлами": "Knotted Rope", "Копченый окунь": "Smoked Snapper",
        "Кофель-нагели": "Belaying Pins", "Подзорная труба": "Spyglass", "Ячменная мука": "Barley Meal",
        "Книга по дрессировке": "Trainer's Book", "Кость существа": "Creature's Bone",
    },
    "Гуль": {
        "Маска Ямори": "Yamori's Mask", "Радужная повязка на глаз": "Iridescent Eye Patch",
        "Инструмент пыток": "Torture Apparatus", "Красноголовая сколопендра": "Red-Headed Centipede",
        "Свежий кофе": "Fresh Coffee", "Удостоверение CCG": "CCG ID Card", "Галстук Амона": "Amon's Necktie",
        "Ликорис лучистый": "Red Spider Lily", "Одежда «Дерево Аогири»": "Aogiri Tree Robe",
        "Очки Ридзэ": "Rize's Glasses", "Перчатка Мадо": "Mado's Glove", "Зонтик Хинами": "Hinami's Umbrella",
        "Мешочек Канэки": "Kaneki's Satchel", "Наушники Хидэ": "Hide's Headphones",
        "Окровавленный носовой платок": "Blood-Stained Handkerchief", "Разованная цепь": "Broken Chain",
        "Бумажник Канэки": "Kaneki's Wallet", "Тайяки": "Taiyaki", "Фартук «Антэйку»": "Anteiku Apron",
        "Яйцо черного козла": "The Black Goat's Egg",
    },
    "Аниматроник": {
        "Фаз-монета": "Faz-Coin", "Радужная «оболочка»": "Iridescent Remnant",
        "Панель доступа": "Access Panel", "Все на праздник! Плакат": "Celebrate! Poster",
        "Процессор Эндо": "Endo CPU", "Сумка с добычей": "Loot Bag",
        "Гитарные струны Бонни": "Bonnie's Guitar Strings", "Слюнявчик Чики": "Chica's Bib",
        "Крюк Фокси": "Foxy's Hook", "Шляпа Фредди": "Freddy's Hat",
        "Рисунок фиолетового": "Purple Guy Drawing", "Офисный телефон": "Office Phone",
        "Колпак для вечеринок": "Party Hat", "Порванная занавеска": "Ripped Curtain",
        "Значок охранника": "Security Guard's Badge", "Цветные ленты": "Streamers",
    },
    "Красу": {
        "Изодранное платье": "Shredded Gown", "Цыплячья голова": "Chicken Head",
        "Гнилая свинья": "Rotten Swine", "Загадочный эликсир": "Mysterious Elixir",
        "Остатки лоренцы": "Lorenza's Remains", "Скипетр королевы": "Queen's Sceptre",
        "Газета в рамке": "Framed Newspaper", "Забрызганный носовой платок": "Spattered Handkerchief",
        "Затупленный нож": "Dulled Knife", "Рука Джанджиры": "Janjira's Hand",
        "Театральный бинокль": "Theatre Binoculars", "Извивающийся паразит": "Wriggling Parasite",
        "Испорченный метроном": "Defective Metronome", "Ошметок Малай": "Chunk of Malai",
        "Свиной глаз": "Pig's Eye", "Скомканные ноты": "Crumpled Sheet Music",
        "Липкая пастилка": "Sticky Lozenge",
    },
    "Первый": {
        "Радужный чип подавления": "Iridescent Soteria Chip", "Шахматная фигурка": "Chess Piece",
        "Останки кролика": "Rabbit Remains", "Ошейник-электрошокер": "Electroshock Collar",
        "Сломанный скейт": "Broken Skateboard", "Черная вдова": "Black Widow Spider",
        "Бритва Виктора": "Victor's Razor Blade", "Колпак с электродами": "Electrode Cap",
        "Очки из пиццерии": "Pizza Goggles", "Поддельное свидетельство о смерти": "Forged Death Certificate",
        "Шейное щупальце": "Neck Tendril", "Окровавленный конек": "Bloody Roller Skate",
        "Раздолбанный кассетник": "Smashed Cassette Deck", "Разобранный суперком": "Gutted Supercom",
        "Сломанная Ракета": "Shattered Wrist Rocket", "Стрелки часов": "Clock Hands",
        "Бейдж санитара": "Orderly ID", "Бисерный лабиринт": "Bead Maze",
        "Винтажный радиоприемник": "Mid-Century Radio", "Витражная роспись": "Stained Glass Mural",
    },
    "Слэшер": {
        "Грязные деньги": "Dirty Money", "Радужный лодочный мотор": "Iridescent Boat Motor",
        "Жетон помощника шерифа": "Deputy's Badge", "Кровавый журнал": "Bloody Magazine",
        "Пропавший штопор": "Missing Corkscrew", "Сгоревший предохранитель": "Burnt Fuse",
        "Глазная слизь": "Eye Goop", "Два гвоздя": "Two Nails", "Камень для сауны": "Sauna Rock",
        "Осколки зеркала": "Mirror Shards (Omnipresent Evil)", "Рельефный алюминий": "Imprinted Aluminum",
        "Кофе коронера": "Coroner's Coffee", "Кровавая улыбка": "Bloody Smile",
        "Праздничная шумелка": "Party Noisemaker", "Спальный мешок": "Sleeping Bag",
        "Токсичные отходы": "Toxic Waste", "Вязальная спица": "Knitting Needle",
        "Погнутое колесо": "Bent Wheel", "Ручной культиватор": "Garden Claw",
        "Туфля санитарки": "Orderly's Shoe",
    },
}

# Аддоны предметов выживших: категория -> {RU: EN}
ITEM_ADDON_RU_EN = {
    "Фонарики": {
        "Аккумулятор с мощным зарядом": "Long Life Battery", "Сверхмощная батарейка": "Heavy Duty Battery",
        "Батарейка": "Battery", "Тонкая нить накаливания": "Low Amp Filament",
        "Странная лампочка": "Odd Bulb", "Кожаная рукоять": "Leather Grip",
        "Фокусирующая линза": "Focus Lens", "Электролампа": "Power Bulb", "Tir оптика": "TIR Optic",
        "Резиновая рукоятка": "Rubber Grip", "Интенсивный галоген": "Intense Halogen",
        "Высококлассные сапфировые линзы": "High-End Sapphire Lens",
    },
    "Аптечки": {
        "Очищенная сыворотка": "Refined Serum", "Самоклеющиеся бинты": "Self Adherent Wrap",
        "Бинты": "Bandages", "Повязки": "Gauze Roll", "Гелевые повязки": "Gel Dressings",
        "Иголка и нитка": "Needle & Thread", "Пластырь-бабочка": "Butterfly Tape",
        "Резиновые перчатки": "Rubber Gloves", "Медицинские ножницы": "Medical Scissors",
        "Кровоостанавливающий препарат": "Styptic Agent", "Укол от усталости": "Anti-Exhaustion Syringe",
        "Губка": "Sponge", "Брюшные повязки": "Abdominal Dressing", "Хирургическая игла": "Surgical Suture",
    },
    "Ящики с инструментами": {
        "Катушка проволоки": "Wire Spool", "Старые запчасти": "Scraps", "Режущая проволока": "Cutting Wire",
        "Ножовка": "Hacksaw", "Защитные перчатки": "Protective Gloves", "Разводной ключ": "Grip Wrench",
        "Шарнирный ключ": "Socket Swivels", "Руководство": "Instructions", "Чистая тряпка": "Clean Rag",
        "Новая деталь": "Brand New Part", "Пружинный зажим": "Spring Clamp",
    },
    "Карты": {
        "Багровая печать": "Crimson Stamp", "Заостренная щепка": "Sharpened Flint",
        "Потрепанная лента": "Battered Tape", "Погрызенный компас": "Gnarled Compass",
        "Светящиеся чернила": "Glowing Ink",
    },
    "Ключи": {
        "Кровавый янтарь": "Blood Amber", "Уникальное обручальное кольцо": "Unique Wedding Ring",
        "Плетеная безделушка": "Braided Bauble", "Пронзительный свист": "Shrill Whistle",
        "Амулет дружбы": "Friendship Charm",
    },
    "Предметы с туманом": {
        "Мощная вытяжка": "Potent Extract", "Грибная смесь": "Mushroom Formula",
        "Маслянистый сок": "Oily Sap", "Реактивное соединение": "Reactive Compound",
        "Вулканический камень": "Volcanic Stone",
    },
}
