# -*- coding: utf-8 -*-
"""Карта «русское имя навыка -> внутренний ID иконки».

Источник: сырой викитекст страниц RU-вики «Навыки убийц» и «Навыки выживших»
(пары [[file:...|link=РУСКОЕ ИМЯ]]). Имена файлов там fandom-овские, а доступный
CDN — deadbydaylight.wiki.gg, где те же иконки лежат под другими именами
(IconPerks_<ID>.png / T_UI_iconsPerks_<ID>.png). Поэтому здесь хранится только
внутренний ID, а реальный файл подбирает resolve_icons.py по нормализованному ID.

Служебный файл для генерации dbd_icons.py; в рантайме не используется.
"""

# RU имя -> (внутренний ID иконки, исходное имя файла на RU-вики)
PERK_ICON_IDS = {
    # ============================== УБИЙЦЫ: уникальные ==============================
    "Нетерпимость": "agitation", "Зверская сила": "brutalstrength",
    "Пугающее присутствие": "unnerving",
    "Детище тьмы": "shadowborn", "Ищейка": "bloodhound", "Хищник": "predator",
    "Стойкий": "hb1", "Детище света": "hb2", "Умелец": "hb3",
    "Стридор": "stridor", "Танатофобия": "thanatophobia", "Зов медсестры": "nurses-calling",
    "Оставьте лучшее напоследок": "Save_best_for_last", "Угасающий свет": "Dying_light_killer",
    "Поиграть со своей жертвой": "Play_with_your_food_killer",
    "Порча: погибель": "Ruin", "Порча: пожирание надежды": "Devourhope",
    "Порча: третья печать": "Thethirdseal",
    "Слежка и наказание": "monitorabuse", "Перегрузка": "generationOvercharge",
    "Невыносимое присутствие": "overwhelmingP",
    "Территориальный императив": "IconPerk_1", "Порча: колыбельная охотницы": "IconPerk_2",
    "Хищный зверь": "IconPerk_3",
    "Барбекю и чили": "BBQAndChili", "Гибель Франклина": "franklinsDemise", "Нокаут": "knockOut",
    "Яркое пламя": "fireupmanual", "Помни меня": "remembermemanual",
    "Кровавый смотритель": "bloodwardenmanual",
    "Выбор за тобой": "makeyourchoice", "Наблюдение": "serveillance",
    "Секущий крюк: секрет палача": "hangmanstrick",
    "Чертик из табакерки": "popGoesTheWeasel", "Клоунофобия": "coulrophobia", "Розыгрыш": "bamboozle",
    "Ненависть": "hatred", "Порча: проклятая земля": "hauntedGround", "Ярость духа": "spiritFury",
    "Разлад": "discordance", "Железная дева": "ironMaiden", "Безумное упорство": "madGrit",
    "Темная преданность": "darkDevotion", "Вмешательство скверны": "corruptIntervention",
    "Заразительный ужас": "infectiousFright",
    "Скрытная погоня": "furtiveChase", "Чуткий слух": "imAllEars", "Пугающая тряска": "thrillingTremors",
    "Жестокая изоляция": "cruelConfinement", "Разрушитель разума": "mindBreaker", "Выброс": "surge",
    "Тактика зансин": "zanshinTactics", "Отзвук крови": "bloodEcho", "Возмездие": "nemesis",
    "Порча: кара": "hexRetribution", "Аварийная кнопка": "deadManSwitch", "Знаток техники": "gearHead",
    "Тропа терзаний": "trailOfTorment", "Принудительная мера": "forcedPenance",
    "Смертельные узы": "deathbound",
    "Порча: благоволение крови": "hexBloodFavor", "Порча: не-смерть": "hexUndying",
    "Драконья хватка": "dragonsGrip",
    "Добивание": "coupDeGrace", "Скопидом": "Hoarder", "Притеснение": "Oppression",
    "Фанатение": "Starstruck", "Порча: контроль толпы": "HexCrowdControl", "Выхода нет": "NoWayOut",
    "Подрыв": "eruption", "Истерия": "hysteria", "Преследователь-убийца": "lethalPursuer",
    "Мертвая хватка": "ironGrasp", "Порча: игрушка": "HexPlaything",
    "Секущий крюк: дар боли": "ScourgeHookGiftOfPain",
    "Мрачные объятья": "grimEmbrace", "Секущий крюк: резонанс боли": "painResonance",
    "Порча: пентименто": "hexPentimento",
    "Соленое море": "callOfBrine", "Секущий крюк: пучина ярости": "scourgeHookFloodsOfRage",
    "Безжалостный шторм": "mercilessStorm",
    "Растворение": "Dissolution", "Явление мрака": "DarknessRevelated",
    "Тлетворное касание": "SepticTouch",
    "Лучшая анатомия": "SuperiorAnatomy", "Развитая внимательность": "AwakenedAwarenes",
    "Последний этап": "Terminus",
    "Им не укрыться": "NowhereToHide", "Порча: лик мрака": "HexFaceTheDarkness",
    "Свирепая гордыня": "Hubris",
    "Бац!": "thwack", "Рычаг влияния": "leverage", "Догонялки": "gameAfoot",
    "Генетические ограничения": "GeneticLimits", "Вынужденная нерешительность": "ForcedHesitation",
    "Машинное обучение": "SelfAware",
    "Совершенное оружие": "UltimateWeapon", "Быстрая жестокость": "RapidBrutality",
    "Инстинкт чужого": "AlienInstinct",
    "Порча: игра для двоих": "twoCanPlay", "Друзья до гроба": "friendsTillEnd",
    "Батарейки в комплекте": "battIncluded",
    "Свободное": "Unbound", "Непредвиденное": "Unforeseen", "Незавершенное": "Undone",
    "Связь с плетением": "weaveAttunement", "Безжизненное касание": "languidTouch",
    "Темное высокомерие": "darkArrogance",
    "Алчность": "HumanGreed", "Владычество": "Dominance", "Порча: горькая участь": "HexWretchedFate",
    "Оглушительный гром": "AllShakingThunder",
    "Секущий крюк: щербатый компас": "ScourgeHookJaggedCompass", "Без пощады": "NoQuarter",
    "Порча: только отчаяние": "NothingButMisery", "Переплетенные навсегда": "ForeverEntwined",
    "Все несвободны": "NoneAreFree",
    "Требуются работники": "HelpWanted", "Фантомный страх": "PhantomFear", "Неполадки": "Haywire",
    "Голод": "Ravenous", "Блуждающий взгляд": "WanderingEye",
    "Порча: предвестие рока": "HexOvertureOfDoom",
    "Перевести часы назад": "TurnBackTheClock", "Секретный проект": "SecretProject",
    "Порча: разум улья": "HexHiveMind",
    "Порча: смертельный испуг": "ScaredToDeath", "Безмолвная тень": "SilentShadow",
    "Неистовство": "Rampage",
    "Небесный свидетель": "CelestialWitness", "Порча: в твоей власти": "HexUnderYourThumb",
    "Опустошение": "LayWaste",
    # ============================== УБИЙЦЫ: общие ==============================
    "Тихий шорох": "bitterMurmur", "Охотник на оленей": "deerstalker", "Сеющий страх": "distressing",
    "Коварство": "insidious", "Секущий крюк: чудовищный храм": "monstrousShrine",
    "Порча: никому не скрыться от смерти": "noOneEscapesDeath",
    "Небрежный мясник": "sloppyButcher", "Сумеречные шпионы": "spiesFromTheShadows",
    "Порча: охотничий азарт": "thrillOfTheHunt", "Безжалостный": "unrelenting",
    "Шепоты": "whispers", "Разбитые надежды": "shatteredHope",
    # ============================== ВЫЖИВШИЕ: уникальные ==============================
    "Связь": "bond", "Прояви себя": "provetyself", "Лидер": "leader",
    "Адреналин": "adrenaline", "Быстрый и тихий": "quickandquiet", "Спринтер": "sprintburst",
    "Познания в ботанике": "botanyknowledge", "Сострадание": "empathy", "Сам себе доктор": "selfcare",
    "Спокойствие духа": "calmwill", "Железная воля": "ironwill", "Крушитель": "saboteur",
    "Ловкое приземление": "Balanced_landing", "Городской бег": "Urban_evasion",
    "Уроки улиц": "Streetwise",
    "Единственный выживший": "Sole_survivor", "Решающий удар": "Decisive_strike",
    "Объект одержимости": "Object_obsession",
    "Туз в рукаве": "Aceinthehole", "Повысить ставки": "Uptheante", "Игра в открытую": "Adb_open_handed",
    "Одолженное время": "borrowedTime", "Оставленный позади": "leftBehind", "Несокрушимый": "unbreakable",
    "Тревога": "alert", "Гибкость": "lithe", "Техник": "technician",
    "Мы будем жить вечно": "WGLF", "Крепкий орешек": "deadHard", "Без сожаления": "NoMither",
    "Аптекарь": "pharmacy", "Бессонница": "vigil", "Проснись": "wakeup",
    "Выдержка": "tenacity", "Детективное чутье": "detectiveshunch",
    "Выслеживание подозреваемого": "stakeout",
    "Потанцуй со мной": "danceWithMe", "Уникальная возможность": "windowsOfOpportunity",
    "Через край": "boilOver",
    "Самоучка": "autodidact", "Освобождение": "deliverance", "Диверсия": "diversion",
    "Уход за больным": "aftercare", "Поломка": "breakdown", "Искажение": "distortion",
    "Солидарность": "solidarity", "Равновесие": "poised", "Напролом": "headOn",
    "Раскачка": "flipFlop", "Пристегнись": "buckleUp", "Проверка на прочность": "mettleOfMan",
    "Нянька": "babySitter", "Товарищество": "camaraderie", "Второе дыхание": "secondWind",
    "Лучше вместе": "betterTogether", "Фиксация": "fixated", "Внутренняя сила": "innerStrength",
    "Любыми средствами": "anyMeansNecessary", "Форсаж": "breakout", "Везение": "luckyBreak",
    "Ради людей": "forThePeople", "Обман во благо": "redHerring", "Без огласки": "offTheRecord",
    "Оберег души": "soulGuard", "Кровавый договор": "bloodPact", "Скрытый союз": "repressedAlliance",
    "Строим на века": "builtToLast", "Отчаянные меры": "desperateMeasures", "Визионер": "visionary",
    "Изучение": "appraisal", "Уловка": "deception", "Отчаянная борьба": "powerStruggle",
    "За чужой счет": "FastTrack", "Ударный забег": "SmashHit", "Самосохранение": "Self-Preservation",
    "Стиснув зубы": "BiteTheBullet", "Световая граната": "Flashbang", "Дух новичка": "RookieSpirit",
    "Фугасная мина": "blastMine", "Поправка": "Resurgence", "Противодействие": "Counterforce",
    "Ясновидение": "Clairvoyance", "Дар: круг исцеления": "BoonCircleOfHealing",
    "Дар: уход в тень": "BoonShadowStep",
    "Преодоление": "Overcome", "Корректировка": "CorrectiveAction", "Дар: экспонента": "BoonExponential",
    "Дар: теория мрака": "darkTheory", "Эмпатическая связь": "empathicConnection",
    "Родительская забота": "parentalGuidance",
    "Собранность": "InnerFocus", "Остаточное проявление": "ResidualManifest", "Усердие": "Overzealous",
    "Жучок": "Wiretap", "Ниже травы": "LowProfile", "Поспешное лечение": "ReactiveHealing",
    "Как новенький": "BetterThanNew", "Ободрение": "Reassurance",
    "Полная сосредоточенность": "Hyperfocus",
    "Потенциальная энергия": "PotentialEnergy", "Умудренный туманом": "Fogwise",
    "Быстрый гамбит": "quickGambit",
    "На волю": "cutLoose", "Командная работа: быстрая пара": "teamworkPowerOfTwo",
    "Дружеское состязание": "friendlyCompetition",
    "Запасной игрок": "backgroundPlayer",
    "Командная работа: общая скрытность": "teamworkCollectiveStealth", "Выше головы": "bloodRush",
    "Ремонтник": "troubleshooter", "Призвание": "madeForThis", "Утилизатор": "scavenger",
    "Драматургия": "Dramaturgy", "Партнер по сцене": "ScenePartner", "Вот это поворот": "PlotTwist",
    "Счастливая звезда": "LuckyStar", "Химическая ловушка": "ChemicalTrap", "Легкоступ": "LightFooted",
    "Воин света": "champOfLight", "Дар: освещение": "Illumination", "Дедлайн": "Deadline",
    "Чары: пауки-прядильщики": "InvWeavingSpiders", "Сила во мраке": "StrengthInShadows",
    "Дерзость": "Wicked",
    "Зеркальная иллюзия": "mirroredIllusion", "Вдохновение барда": "bardicInspiration",
    "Замри и увидишь": "stillSight",
    "Сноровка": "finesse", "Специалист": "specialist", "Закалка": "hardened",
    "Глаза Бельмонта": "EyesOfBelmont", "Ликование": "Exultation", "Момент славы": "MomentOfGlory",
    "Чары: предательские вороны": "InvocationTreacherousCrows", "С чистого листа": "CleanBreak",
    "Бремя на себя": "ShoulderTheBurden",
    "Не навреди": "DoNoHarm", "Врачебный долг": "DutyOfCare", "Быстрое реагирование": "RapidResponse",
    "Командная работа: собраться с силами": "TeamworkThrowDown",
    "Апокалиптическая смекалка": "ApocalypticIngenuity", "Эй, я здесь!": "ComeAndGetMe",
    "Убежденность": "Conviction", "Последний рубеж": "LastStand",
    "Командная работа: скромная победа": "TeamworkToughenUp",
    "Жизнь в дороге": "roadLife", "Раз, два, три, четыре!": "oneTwoThreeFour",
    "Записки о призраке": "ghostNotes",
    "Бада-бада-бум": "BadaBadaBoom", "Изменение плана": "ChangeOfPlan",
    "Командная работа: полная схема": "TeamworkFullCircuit",
    "Восприятие экстрасенса": "extrasensoryPerception", "Мы тебя видим": "weSeeYou",
    "Командная работа: приглушение": "teamworkSoftSpoken",
    "Место для нас": "aPlaceForUs", "На пять шагов впереди": "FiveMovesAhead",
    "Состояние потока": "FlowState",
    "Полный газ!": "WideOpenThrottle", "Оказание помощи": "LendaHand",
    "Перекрестный допрос": "CrossExamination",
    "Дар: непоколебимость": "BoonSteadfast", "Зов на помощь": "SalvationsCry",
    "Плоды трудов": "FruitsOfYourLabor",
    # ============================== ВЫЖИВШИЕ: общие ==============================
    "Темное чувство": "darkSense", "Дежавю": "dejaVu", "Надежда": "hope", "Кровные узы": "kindred",
    "Легковес": "lightweight", "Этому не бывать": "thisIsNotHappening", "Мы справимся": "wellMakeIt",
    "Предчувствие": "premonition", "Устойчивость": "resilience", "Скользкое мясо": "slipperyMeat2",
    "Мелкая дичь": "smallGame", "Мурашки по спине": "spineChill",
    "Никто не остался позади": "noOneLeftBehind", "Мародерское чутье": "plunderersInstinct",
}

# Имена, в которых RU-вики расходится с тем, что было в базе v2 (исправлено по вики).
NAME_FIXES = {
    "Невероятная стойкость": "Нетерпимость",
    "Порча: тотем охоты": "Пугающее присутствие",
    "Заряд бодрости": "Детище света",
    "Тиннитус": "Умелец",
    "Секущий крюк: резонанс боли (Близнецы)": "Скопидом",
    "Птичий глаз": "Секущий крюк: резонанс боли",
    "Чудовищный храм": "Секущий крюк: чудовищный храм",
    "Чары пауки-прядильщики": "Чары: пауки-прядильщики",
    "Чары предательские вороны": "Чары: предательские вороны",
    "Тёмная преданность": "Темная преданность",
    "Мёртвая хватка": "Мертвая хватка",
    "Тёмное высокомерие": "Темное высокомерие",
    "Зов медсестры ": "Зов медсестры",
    "Крик спасения": "Зов на помощь",
    "Дар: стойкость": "Дар: непоколебимость",
    "Сейбл Уорд": "Сейбл Уорд",
    "Судья": "Правосудие",
    "Порча: под моим каблуком": "Порча: в твоей власти",
    "Разорение": "Опустошение",
}
